// <auto-generated />
// This file is auto generated, do not edit.
#nullable enable
using System;
using System.Buffers;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using OpenTK.Audio;
using OpenTK.Core.Native;
using OpenTK.Mathematics;

namespace OpenTK.Audio.OpenAL
{
    public readonly unsafe partial struct ALPointers
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ALPointers"/> struct.
        /// </summary>
        internal ALPointers(delegate* unmanaged[Cdecl]<byte*, void*> loadFunction)
        {
            fixed (byte* names = AllFunctionNames)
            {
                
                var alBuffer3f_fnptr = (delegate* unmanaged[Cdecl]<int, int, float, float, float, void>)loadFunction(names + alBuffer3f_offset);
                _alBuffer3f_fnptr = alBuffer3f_fnptr;
                if (alBuffer3f_fnptr is not null)
                {
                    _alBuffer3i_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, int, int, void>)loadFunction(names + alBuffer3i_offset);
                    _alBufferData_fnptr = (delegate* unmanaged[Cdecl]<int, int, void*, int, int, void>)loadFunction(names + alBufferData_offset);
                    _alBufferf_fnptr = (delegate* unmanaged[Cdecl]<int, int, float, void>)loadFunction(names + alBufferf_offset);
                    _alBufferfv_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunction(names + alBufferfv_offset);
                    _alBufferi_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, void>)loadFunction(names + alBufferi_offset);
                    _alBufferiv_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunction(names + alBufferiv_offset);
                    _alDeleteBuffers_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunction(names + alDeleteBuffers_offset);
                    _alDeleteSources_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunction(names + alDeleteSources_offset);
                    _alDisable_fnptr = (delegate* unmanaged[Cdecl]<int, void>)loadFunction(names + alDisable_offset);
                    _alDistanceModel_fnptr = (delegate* unmanaged[Cdecl]<int, void>)loadFunction(names + alDistanceModel_offset);
                    _alDopperFactor_fnptr = (delegate* unmanaged[Cdecl]<float, void>)loadFunction(names + alDopperFactor_offset);
                    _alEnable_fnptr = (delegate* unmanaged[Cdecl]<int, void>)loadFunction(names + alEnable_offset);
                    _alGenBuffers_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunction(names + alGenBuffers_offset);
                    _alGenSources_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunction(names + alGenSources_offset);
                    _alGetBoolean_fnptr = (delegate* unmanaged[Cdecl]<int, byte>)loadFunction(names + alGetBoolean_offset);
                    _alGetBooleanv_fnptr = (delegate* unmanaged[Cdecl]<int, byte*, void>)loadFunction(names + alGetBooleanv_offset);
                    _alGetBuffer3f_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, float*, float*, void>)loadFunction(names + alGetBuffer3f_offset);
                    _alGetBuffer3i_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, int*, int*, void>)loadFunction(names + alGetBuffer3i_offset);
                    _alGetBufferf_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunction(names + alGetBufferf_offset);
                    _alGetBufferfv_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunction(names + alGetBufferfv_offset);
                    _alGetBufferi_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunction(names + alGetBufferi_offset);
                    _alGetBufferiv_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunction(names + alGetBufferiv_offset);
                    _alGetDouble_fnptr = (delegate* unmanaged[Cdecl]<int, double>)loadFunction(names + alGetDouble_offset);
                    _alGetDoublev_fnptr = (delegate* unmanaged[Cdecl]<int, double*, void>)loadFunction(names + alGetDoublev_offset);
                    _alGetEnumValue_fnptr = (delegate* unmanaged[Cdecl]<byte*, int>)loadFunction(names + alGetEnumValue_offset);
                    _alGetError_fnptr = (delegate* unmanaged[Cdecl]<int>)loadFunction(names + alGetError_offset);
                    _alGetFloat_fnptr = (delegate* unmanaged[Cdecl]<int, float>)loadFunction(names + alGetFloat_offset);
                    _alGetFloatv_fnptr = (delegate* unmanaged[Cdecl]<int, float*, void>)loadFunction(names + alGetFloatv_offset);
                    _alGetInteger_fnptr = (delegate* unmanaged[Cdecl]<int, int>)loadFunction(names + alGetInteger_offset);
                    _alGetIntegerv_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunction(names + alGetIntegerv_offset);
                    _alGetListener3f_fnptr = (delegate* unmanaged[Cdecl]<int, float*, float*, float*, void>)loadFunction(names + alGetListener3f_offset);
                    _alGetListener3i_fnptr = (delegate* unmanaged[Cdecl]<int, int*, int*, int*, void>)loadFunction(names + alGetListener3i_offset);
                    _alGetListenerf_fnptr = (delegate* unmanaged[Cdecl]<int, float*, void>)loadFunction(names + alGetListenerf_offset);
                    _alGetListenerfv_fnptr = (delegate* unmanaged[Cdecl]<int, float*, void>)loadFunction(names + alGetListenerfv_offset);
                    _alGetListeneri_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunction(names + alGetListeneri_offset);
                    _alGetListeneriv_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunction(names + alGetListeneriv_offset);
                    _alGetProcAddress_fnptr = (delegate* unmanaged[Cdecl]<byte*, void*>)loadFunction(names + alGetProcAddress_offset);
                    _alGetSource3f_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, float*, float*, void>)loadFunction(names + alGetSource3f_offset);
                    _alGetSource3i_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, int*, int*, void>)loadFunction(names + alGetSource3i_offset);
                    _alGetSourcef_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunction(names + alGetSourcef_offset);
                    _alGetSourcefv_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunction(names + alGetSourcefv_offset);
                    _alGetSourcei_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunction(names + alGetSourcei_offset);
                    _alGetSourceiv_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunction(names + alGetSourceiv_offset);
                    _alGetString_fnptr = (delegate* unmanaged[Cdecl]<int, byte*>)loadFunction(names + alGetString_offset);
                    _alIsBuffer_fnptr = (delegate* unmanaged[Cdecl]<int, byte>)loadFunction(names + alIsBuffer_offset);
                    _alIsEnabled_fnptr = (delegate* unmanaged[Cdecl]<int, byte>)loadFunction(names + alIsEnabled_offset);
                    _alIsExtensionPresent_fnptr = (delegate* unmanaged[Cdecl]<byte*, byte>)loadFunction(names + alIsExtensionPresent_offset);
                    _alIsSource_fnptr = (delegate* unmanaged[Cdecl]<int, byte>)loadFunction(names + alIsSource_offset);
                    _alListener3f_fnptr = (delegate* unmanaged[Cdecl]<int, float, float, float, void>)loadFunction(names + alListener3f_offset);
                    _alListener3i_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, int, void>)loadFunction(names + alListener3i_offset);
                    _alListenerf_fnptr = (delegate* unmanaged[Cdecl]<int, float, void>)loadFunction(names + alListenerf_offset);
                    _alListenerfv_fnptr = (delegate* unmanaged[Cdecl]<int, float*, void>)loadFunction(names + alListenerfv_offset);
                    _alListeneri_fnptr = (delegate* unmanaged[Cdecl]<int, int, void>)loadFunction(names + alListeneri_offset);
                    _alListeneriv_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunction(names + alListeneriv_offset);
                    _alSource3f_fnptr = (delegate* unmanaged[Cdecl]<int, int, float, float, float, void>)loadFunction(names + alSource3f_offset);
                    _alSource3i_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, int, int, void>)loadFunction(names + alSource3i_offset);
                    _alSourcef_fnptr = (delegate* unmanaged[Cdecl]<int, int, float, void>)loadFunction(names + alSourcef_offset);
                    _alSourcefv_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunction(names + alSourcefv_offset);
                    _alSourcei_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, void>)loadFunction(names + alSourcei_offset);
                    _alSourceiv_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunction(names + alSourceiv_offset);
                    _alSourcePause_fnptr = (delegate* unmanaged[Cdecl]<int, void>)loadFunction(names + alSourcePause_offset);
                    _alSourcePausev_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunction(names + alSourcePausev_offset);
                    _alSourcePlay_fnptr = (delegate* unmanaged[Cdecl]<int, void>)loadFunction(names + alSourcePlay_offset);
                    _alSourcePlayv_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunction(names + alSourcePlayv_offset);
                    _alSourceQueueBuffers_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunction(names + alSourceQueueBuffers_offset);
                    _alSourceRewind_fnptr = (delegate* unmanaged[Cdecl]<int, void>)loadFunction(names + alSourceRewind_offset);
                    _alSourceRewindv_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunction(names + alSourceRewindv_offset);
                    _alSourceStop_fnptr = (delegate* unmanaged[Cdecl]<int, void>)loadFunction(names + alSourceStop_offset);
                    _alSourceStopv_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunction(names + alSourceStopv_offset);
                    _alSourceUnqueueBuffers_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunction(names + alSourceUnqueueBuffers_offset);
                    _alSpeedOfSound_fnptr = (delegate* unmanaged[Cdecl]<float, void>)loadFunction(names + alSpeedOfSound_offset);
                }
                
                _EAXGet_fnptr = (delegate* unmanaged[Cdecl]<Guid*, uint, uint, void*, uint, int>)loadFunction(names + EAXGet_offset);
                _EAXSet_fnptr = (delegate* unmanaged[Cdecl]<Guid*, uint, uint, void*, uint, int>)loadFunction(names + EAXSet_offset);
                
                _EAXGetBufferMode_fnptr = (delegate* unmanaged[Cdecl]<int, int*, int>)loadFunction(names + EAXGetBufferMode_offset);
                _EAXSetBufferMode_fnptr = (delegate* unmanaged[Cdecl]<int, int*, int, byte>)loadFunction(names + EAXSetBufferMode_offset);
                
                var alAuxiliaryEffectSlotf_fnptr = (delegate* unmanaged[Cdecl]<int, int, float, void>)loadFunction(names + alAuxiliaryEffectSlotf_offset);
                _alAuxiliaryEffectSlotf_fnptr = alAuxiliaryEffectSlotf_fnptr;
                if (alAuxiliaryEffectSlotf_fnptr is not null)
                {
                    _alAuxiliaryEffectSlotfv_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunction(names + alAuxiliaryEffectSlotfv_offset);
                    _alAuxiliaryEffectSloti_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, void>)loadFunction(names + alAuxiliaryEffectSloti_offset);
                    _alAuxiliaryEffectSlotiv_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunction(names + alAuxiliaryEffectSlotiv_offset);
                    _alDeleteAuxiliaryEffectSlots_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunction(names + alDeleteAuxiliaryEffectSlots_offset);
                    _alDeleteEffects_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunction(names + alDeleteEffects_offset);
                    _alDeleteFilters_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunction(names + alDeleteFilters_offset);
                    _alEffectf_fnptr = (delegate* unmanaged[Cdecl]<int, int, float, void>)loadFunction(names + alEffectf_offset);
                    _alEffectfv_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunction(names + alEffectfv_offset);
                    _alEffecti_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, void>)loadFunction(names + alEffecti_offset);
                    _alEffectiv_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunction(names + alEffectiv_offset);
                    _alFilterf_fnptr = (delegate* unmanaged[Cdecl]<int, int, float, void>)loadFunction(names + alFilterf_offset);
                    _alFilterfv_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunction(names + alFilterfv_offset);
                    _alFilteri_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, void>)loadFunction(names + alFilteri_offset);
                    _alFilteriv_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunction(names + alFilteriv_offset);
                    _alGenAuxiliaryEffectSlots_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunction(names + alGenAuxiliaryEffectSlots_offset);
                    _alGenEffects_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunction(names + alGenEffects_offset);
                    _alGenFilters_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunction(names + alGenFilters_offset);
                    _alGetAuxiliaryEffectSlotf_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunction(names + alGetAuxiliaryEffectSlotf_offset);
                    _alGetAuxiliaryEffectSlotfv_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunction(names + alGetAuxiliaryEffectSlotfv_offset);
                    _alGetAuxiliaryEffectSloti_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunction(names + alGetAuxiliaryEffectSloti_offset);
                    _alGetAuxiliaryEffectSlotiv_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunction(names + alGetAuxiliaryEffectSlotiv_offset);
                    _alGetEffectf_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunction(names + alGetEffectf_offset);
                    _alGetEffectfv_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunction(names + alGetEffectfv_offset);
                    _alGetEffecti_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunction(names + alGetEffecti_offset);
                    _alGetEffectiv_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunction(names + alGetEffectiv_offset);
                    _alGetFilterf_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunction(names + alGetFilterf_offset);
                    _alGetFilterfv_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunction(names + alGetFilterfv_offset);
                    _alGetFilteri_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunction(names + alGetFilteri_offset);
                    _alGetFilteriv_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunction(names + alGetFilteriv_offset);
                    _alIsAuxiliaryEffectSlot_fnptr = (delegate* unmanaged[Cdecl]<int, void>)loadFunction(names + alIsAuxiliaryEffectSlot_offset);
                    _alIsEffect_fnptr = (delegate* unmanaged[Cdecl]<int, byte>)loadFunction(names + alIsEffect_offset);
                    _alIsFilter_fnptr = (delegate* unmanaged[Cdecl]<int, void>)loadFunction(names + alIsFilter_offset);
                }
                
                var alDebugMessageCallbackEXT_fnptr = (delegate* unmanaged[Cdecl]<delegate* unmanaged[Cdecl]<All, All, uint, All, nuint, byte*, void*, int>, void*, void>)loadFunction(names + alDebugMessageCallbackEXT_offset);
                _alDebugMessageCallbackEXT_fnptr = alDebugMessageCallbackEXT_fnptr;
                if (alDebugMessageCallbackEXT_fnptr is not null)
                {
                    _alDebugMessageControlEXT_fnptr = (delegate* unmanaged[Cdecl]<int, int, uint, int, uint*, byte, void>)loadFunction(names + alDebugMessageControlEXT_offset);
                    _alDebugMessageInsertEXT_fnptr = (delegate* unmanaged[Cdecl]<int, int, uint, int, byte*, void>)loadFunction(names + alDebugMessageInsertEXT_offset);
                    _alGetDebugMessageLogEXT_fnptr = (delegate* unmanaged[Cdecl]<uint, int, int*, int*, uint*, int*, int*, byte*, uint>)loadFunction(names + alGetDebugMessageLogEXT_offset);
                    _alGetObjectLabelEXT_fnptr = (delegate* unmanaged[Cdecl]<int, uint, int, int*, byte*, void>)loadFunction(names + alGetObjectLabelEXT_offset);
                    _alGetPointerEXT_fnptr = (delegate* unmanaged[Cdecl]<int, void*>)loadFunction(names + alGetPointerEXT_offset);
                    _alGetPointervEXT_fnptr = (delegate* unmanaged[Cdecl]<int, void**, void>)loadFunction(names + alGetPointervEXT_offset);
                    _alObjectLabelEXT_fnptr = (delegate* unmanaged[Cdecl]<int, uint, int, byte*, void>)loadFunction(names + alObjectLabelEXT_offset);
                    _alPopDebugGroupEXT_fnptr = (delegate* unmanaged[Cdecl]<void>)loadFunction(names + alPopDebugGroupEXT_offset);
                    _alPushDebugGroupEXT_fnptr = (delegate* unmanaged[Cdecl]<int, uint, int, byte*, void>)loadFunction(names + alPushDebugGroupEXT_offset);
                }
                
                _alMacOSXGetRenderChannelCount_fnptr = (delegate* unmanaged[Cdecl]<int>)loadFunction(names + alMacOSXGetRenderChannelCount_offset);
                _alMacOSXRenderChannelCount_fnptr = (delegate* unmanaged[Cdecl]<int, void>)loadFunction(names + alMacOSXRenderChannelCount_offset);
                
                _alRequestFoldbackStart_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, float*, delegate* unmanaged[Cdecl]<All, nuint, void>, void>)loadFunction(names + alRequestFoldbackStart_offset);
                _alRequestFoldbackStop_fnptr = (delegate* unmanaged[Cdecl]<void>)loadFunction(names + alRequestFoldbackStop_offset);
                
                _alSourceAddNotification_fnptr = (delegate* unmanaged[Cdecl]<int, uint, delegate* unmanaged[Cdecl]<uint, uint, void*, void>, void*, int>)loadFunction(names + alSourceAddNotification_offset);
                _alSourceRemoveNotification_fnptr = (delegate* unmanaged[Cdecl]<int, uint, delegate* unmanaged[Cdecl]<uint, uint, void*, void>, void*, void>)loadFunction(names + alSourceRemoveNotification_offset);
                
                _alSourceGetRenderingQuality_fnptr = (delegate* unmanaged[Cdecl]<int, int>)loadFunction(names + alSourceGetRenderingQuality_offset);
                _alSourceRenderingQuality_fnptr = (delegate* unmanaged[Cdecl]<int, int, void>)loadFunction(names + alSourceRenderingQuality_offset);
                
                _AttenuationScale_LOKI_fnptr = (delegate* unmanaged[Cdecl]<float, void>)loadFunction(names + AttenuationScale_LOKI_offset);
                
                _BufferDataWithCallback_LOKI_fnptr = (delegate* unmanaged[Cdecl]<int, delegate* unmanaged[Cdecl]<uint, uint, void*, All, uint, int>, void>)loadFunction(names + BufferDataWithCallback_LOKI_offset);
                
                var alBufferCallbackSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, delegate* unmanaged[Cdecl]<void*, void*, nuint, nuint>, void*, void>)loadFunction(names + alBufferCallbackSOFT_offset);
                _alBufferCallbackSOFT_fnptr = alBufferCallbackSOFT_fnptr;
                if (alBufferCallbackSOFT_fnptr is not null)
                {
                    _alGetBuffer3PtrSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, void**, void**, void**, void>)loadFunction(names + alGetBuffer3PtrSOFT_offset);
                    _alGetBufferPtrSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, void**, void>)loadFunction(names + alGetBufferPtrSOFT_offset);
                    _alGetBufferPtrvSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, void**, void>)loadFunction(names + alGetBufferPtrvSOFT_offset);
                }
                
                var alBufferSamplesSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, uint, int, int, int, int, void*, void>)loadFunction(names + alBufferSamplesSOFT_offset);
                _alBufferSamplesSOFT_fnptr = alBufferSamplesSOFT_fnptr;
                if (alBufferSamplesSOFT_fnptr is not null)
                {
                    _alBufferSubSamplesSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, int, int, void*, void>)loadFunction(names + alBufferSubSamplesSOFT_offset);
                    _alGetBufferSamplesSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, int, int, void*, void>)loadFunction(names + alGetBufferSamplesSOFT_offset);
                    _alIsBufferFormatSupportedSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, byte>)loadFunction(names + alIsBufferFormatSupportedSOFT_offset);
                }
                
                _alBufferSubDataSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, void*, int, int, void>)loadFunction(names + alBufferSubDataSOFT_offset);
                
                _alDeferUpdatesSOFT_fnptr = (delegate* unmanaged[Cdecl]<void>)loadFunction(names + alDeferUpdatesSOFT_offset);
                _alProcessUpdatesSOFT_fnptr = (delegate* unmanaged[Cdecl]<void>)loadFunction(names + alProcessUpdatesSOFT_offset);
                
                var alEventCallbackSOFT_fnptr = (delegate* unmanaged[Cdecl]<delegate* unmanaged[Cdecl]<All, uint, uint, nuint, byte*, void*, void>, void*, void>)loadFunction(names + alEventCallbackSOFT_offset);
                _alEventCallbackSOFT_fnptr = alEventCallbackSOFT_fnptr;
                if (alEventCallbackSOFT_fnptr is not null)
                {
                    _alEventControlSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int*, byte, void>)loadFunction(names + alEventControlSOFT_offset);
                    _alGetPointerSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, void*>)loadFunction(names + alGetPointerSOFT_offset);
                    _alGetPointervSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, void**, void>)loadFunction(names + alGetPointervSOFT_offset);
                }
                
                var alGetSource3dSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, double*, double*, double*, void>)loadFunction(names + alGetSource3dSOFT_offset);
                _alGetSource3dSOFT_fnptr = alGetSource3dSOFT_fnptr;
                if (alGetSource3dSOFT_fnptr is not null)
                {
                    _alGetSource3i64SOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, long*, long*, long*, void>)loadFunction(names + alGetSource3i64SOFT_offset);
                    _alGetSourcedSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, double*, void>)loadFunction(names + alGetSourcedSOFT_offset);
                    _alGetSourcedvSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, double*, void>)loadFunction(names + alGetSourcedvSOFT_offset);
                    _alGetSourcei64SOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, long*, void>)loadFunction(names + alGetSourcei64SOFT_offset);
                    _alGetSourcei64vSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, long*, void>)loadFunction(names + alGetSourcei64vSOFT_offset);
                    _alSource3dSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, double, double, double, void>)loadFunction(names + alSource3dSOFT_offset);
                    _alSource3i64SOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, long, long, long, void>)loadFunction(names + alSource3i64SOFT_offset);
                    _alSourcedSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, double, void>)loadFunction(names + alSourcedSOFT_offset);
                    _alSourcedvSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, double*, void>)loadFunction(names + alSourcedvSOFT_offset);
                    _alSourcei64SOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, long, void>)loadFunction(names + alSourcei64SOFT_offset);
                    _alSourcei64vSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, long*, void>)loadFunction(names + alSourcei64vSOFT_offset);
                }
                
                _alGetStringiSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, byte*>)loadFunction(names + alGetStringiSOFT_offset);
                
                _alSourcePlayAtTimeSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, long, void>)loadFunction(names + alSourcePlayAtTimeSOFT_offset);
                _alSourcePlayAtTimevSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int*, long, void>)loadFunction(names + alSourcePlayAtTimevSOFT_offset);
                
                var alBuffer3fDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float, float, float, void>)loadFunction(names + alBuffer3fDirect_offset);
                _alBuffer3fDirect_fnptr = alBuffer3fDirect_fnptr;
                if (alBuffer3fDirect_fnptr is not null)
                {
                    _alBuffer3iDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, int, int, void>)loadFunction(names + alBuffer3iDirect_offset);
                    _alBufferDataDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, void*, int, int, void>)loadFunction(names + alBufferDataDirect_offset);
                    _alBufferfDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float, void>)loadFunction(names + alBufferfDirect_offset);
                    _alBufferfvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunction(names + alBufferfvDirect_offset);
                    _alBufferiDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, void>)loadFunction(names + alBufferiDirect_offset);
                    _alBufferivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunction(names + alBufferivDirect_offset);
                    _alDeleteBuffersDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunction(names + alDeleteBuffersDirect_offset);
                    _alDeleteSourcesDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunction(names + alDeleteSourcesDirect_offset);
                    _alDisableDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void>)loadFunction(names + alDisableDirect_offset);
                    _alDistanceModelDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void>)loadFunction(names + alDistanceModelDirect_offset);
                    _alDopperFactorDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, float, void>)loadFunction(names + alDopperFactorDirect_offset);
                    _alEnableDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void>)loadFunction(names + alEnableDirect_offset);
                    _alGenBuffersDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunction(names + alGenBuffersDirect_offset);
                    _alGenSourcesDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunction(names + alGenSourcesDirect_offset);
                    _alGetBooleanDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, byte>)loadFunction(names + alGetBooleanDirect_offset);
                    _alGetBooleanvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, byte*, void>)loadFunction(names + alGetBooleanvDirect_offset);
                    _alGetBuffer3fDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, float*, float*, void>)loadFunction(names + alGetBuffer3fDirect_offset);
                    _alGetBuffer3iDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, int*, int*, void>)loadFunction(names + alGetBuffer3iDirect_offset);
                    _alGetBufferfDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunction(names + alGetBufferfDirect_offset);
                    _alGetBufferfvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunction(names + alGetBufferfvDirect_offset);
                    _alGetBufferiDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunction(names + alGetBufferiDirect_offset);
                    _alGetBufferivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunction(names + alGetBufferivDirect_offset);
                    _alGetDoubleDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, double>)loadFunction(names + alGetDoubleDirect_offset);
                    _alGetDoublevDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, double*, void>)loadFunction(names + alGetDoublevDirect_offset);
                    _alGetEnumValueDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte*, int>)loadFunction(names + alGetEnumValueDirect_offset);
                    _alGetErrorDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int>)loadFunction(names + alGetErrorDirect_offset);
                    _alGetFloatDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, float>)loadFunction(names + alGetFloatDirect_offset);
                    _alGetFloatvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, float*, void>)loadFunction(names + alGetFloatvDirect_offset);
                    _alGetIntegerDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int>)loadFunction(names + alGetIntegerDirect_offset);
                    _alGetIntegervDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunction(names + alGetIntegervDirect_offset);
                    _alGetListener3fDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, float*, float*, float*, void>)loadFunction(names + alGetListener3fDirect_offset);
                    _alGetListener3iDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, int*, int*, void>)loadFunction(names + alGetListener3iDirect_offset);
                    _alGetListenerfDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, float*, void>)loadFunction(names + alGetListenerfDirect_offset);
                    _alGetListenerfvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, float*, void>)loadFunction(names + alGetListenerfvDirect_offset);
                    _alGetListeneriDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunction(names + alGetListeneriDirect_offset);
                    _alGetListenerivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunction(names + alGetListenerivDirect_offset);
                    _alGetProcAddressDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte*, void*>)loadFunction(names + alGetProcAddressDirect_offset);
                    _alGetSource3fDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, float*, float*, void>)loadFunction(names + alGetSource3fDirect_offset);
                    _alGetSource3iDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, int*, int*, void>)loadFunction(names + alGetSource3iDirect_offset);
                    _alGetSourcefDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunction(names + alGetSourcefDirect_offset);
                    _alGetSourcefvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunction(names + alGetSourcefvDirect_offset);
                    _alGetSourceiDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunction(names + alGetSourceiDirect_offset);
                    _alGetSourceivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunction(names + alGetSourceivDirect_offset);
                    _alGetStringDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, byte*>)loadFunction(names + alGetStringDirect_offset);
                    _alIsBufferDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, byte>)loadFunction(names + alIsBufferDirect_offset);
                    _alIsEnabledDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, byte>)loadFunction(names + alIsEnabledDirect_offset);
                    _alIsExtensionPresentDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte*, byte>)loadFunction(names + alIsExtensionPresentDirect_offset);
                    _alIsSourceDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, byte>)loadFunction(names + alIsSourceDirect_offset);
                    _alListener3fDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, float, float, float, void>)loadFunction(names + alListener3fDirect_offset);
                    _alListener3iDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, int, void>)loadFunction(names + alListener3iDirect_offset);
                    _alListenerfDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, float, void>)loadFunction(names + alListenerfDirect_offset);
                    _alListenerfvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, float*, void>)loadFunction(names + alListenerfvDirect_offset);
                    _alListeneriDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, void>)loadFunction(names + alListeneriDirect_offset);
                    _alListenerivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunction(names + alListenerivDirect_offset);
                    _alSource3fDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float, float, float, void>)loadFunction(names + alSource3fDirect_offset);
                    _alSource3iDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, int, int, void>)loadFunction(names + alSource3iDirect_offset);
                    _alSourcefDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float, void>)loadFunction(names + alSourcefDirect_offset);
                    _alSourcefvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunction(names + alSourcefvDirect_offset);
                    _alSourceiDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, void>)loadFunction(names + alSourceiDirect_offset);
                    _alSourceivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunction(names + alSourceivDirect_offset);
                    _alSourcePauseDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void>)loadFunction(names + alSourcePauseDirect_offset);
                    _alSourcePausevDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunction(names + alSourcePausevDirect_offset);
                    _alSourcePlayDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void>)loadFunction(names + alSourcePlayDirect_offset);
                    _alSourcePlayvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunction(names + alSourcePlayvDirect_offset);
                    _alSourceQueueBuffersDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunction(names + alSourceQueueBuffersDirect_offset);
                    _alSourceRewindDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void>)loadFunction(names + alSourceRewindDirect_offset);
                    _alSourceRewindvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunction(names + alSourceRewindvDirect_offset);
                    _alSourceStopDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void>)loadFunction(names + alSourceStopDirect_offset);
                    _alSourceStopvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunction(names + alSourceStopvDirect_offset);
                    _alSourceUnqueueBuffersDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunction(names + alSourceUnqueueBuffersDirect_offset);
                    _alSpeedOfSoundDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, float, void>)loadFunction(names + alSpeedOfSoundDirect_offset);
                    
                    var alDebugMessageCallbackDirectEXT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, delegate* unmanaged[Cdecl]<All, All, uint, All, nuint, byte*, void*, int>, void*, void>)loadFunction(names + alDebugMessageCallbackDirectEXT_offset);
                    _alDebugMessageCallbackDirectEXT_fnptr = alDebugMessageCallbackDirectEXT_fnptr;
                    if (alDebugMessageCallbackDirectEXT_fnptr is not null)
                    {
                        _alDebugMessageControlDirectEXT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, uint, int, uint*, byte, void>)loadFunction(names + alDebugMessageControlDirectEXT_offset);
                        _alDebugMessageInsertDirectEXT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, uint, int, byte*, void>)loadFunction(names + alDebugMessageInsertDirectEXT_offset);
                        _alGetDebugMessageLogDirectEXT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, uint, int, int*, int*, uint*, int*, int*, byte*, uint>)loadFunction(names + alGetDebugMessageLogDirectEXT_offset);
                        _alGetObjectLabelDirectEXT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, uint, int, int*, byte*, void>)loadFunction(names + alGetObjectLabelDirectEXT_offset);
                        _alGetPointerDirectEXT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void*>)loadFunction(names + alGetPointerDirectEXT_offset);
                        _alGetPointervDirectEXT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void**, void>)loadFunction(names + alGetPointervDirectEXT_offset);
                        _alObjectLabelDirectEXT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, uint, int, byte*, void>)loadFunction(names + alObjectLabelDirectEXT_offset);
                        _alPopDebugGroupDirectEXT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void>)loadFunction(names + alPopDebugGroupDirectEXT_offset);
                        _alPushDebugGroupDirectEXT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, uint, int, byte*, void>)loadFunction(names + alPushDebugGroupDirectEXT_offset);
                    }
                    
                    _alRequestFoldbackStartDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, float*, delegate* unmanaged[Cdecl]<All, nuint, void>, void>)loadFunction(names + alRequestFoldbackStartDirect_offset);
                    _alRequestFoldbackStopDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void>)loadFunction(names + alRequestFoldbackStopDirect_offset);
                    
                    _alSourceAddNotificationDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, uint, delegate* unmanaged[Cdecl]<uint, uint, void*, void>, void*, int>)loadFunction(names + alSourceAddNotificationDirect_offset);
                    _alSourceRemoveNotificationDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, uint, delegate* unmanaged[Cdecl]<uint, uint, void*, void>, void*, void>)loadFunction(names + alSourceRemoveNotificationDirect_offset);
                    
                    _alSourceGetRenderingQualityDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int>)loadFunction(names + alSourceGetRenderingQualityDirect_offset);
                    _alSourceRenderingQualityDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, void>)loadFunction(names + alSourceRenderingQualityDirect_offset);
                    
                    _AttenuationScale_DirectLOKI_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, float, void>)loadFunction(names + AttenuationScale_DirectLOKI_offset);
                    
                    _BufferDataWithCallback_DirectLOKI_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, delegate* unmanaged[Cdecl]<uint, uint, void*, All, uint, int>, void>)loadFunction(names + BufferDataWithCallback_DirectLOKI_offset);
                    
                    var alBufferSamplesDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, uint, int, int, int, int, void*, void>)loadFunction(names + alBufferSamplesDirectSOFT_offset);
                    _alBufferSamplesDirectSOFT_fnptr = alBufferSamplesDirectSOFT_fnptr;
                    if (alBufferSamplesDirectSOFT_fnptr is not null)
                    {
                        _alBufferSubSamplesDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, int, int, void*, void>)loadFunction(names + alBufferSubSamplesDirectSOFT_offset);
                        _alGetBufferSamplesDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, int, int, void*, void>)loadFunction(names + alGetBufferSamplesDirectSOFT_offset);
                        _alIsBufferFormatSupportedDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, byte>)loadFunction(names + alIsBufferFormatSupportedDirectSOFT_offset);
                    }
                    
                    _alBufferSubDataDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, void*, int, int, void>)loadFunction(names + alBufferSubDataDirectSOFT_offset);
                    
                    var alBufferCallbackDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, delegate* unmanaged[Cdecl]<void*, void*, nuint, nuint>, void*, void>)loadFunction(names + alBufferCallbackDirectSOFT_offset);
                    _alBufferCallbackDirectSOFT_fnptr = alBufferCallbackDirectSOFT_fnptr;
                    if (alBufferCallbackDirectSOFT_fnptr is not null)
                    {
                        _alGetBuffer3PtrDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, void**, void**, void**, void>)loadFunction(names + alGetBuffer3PtrDirectSOFT_offset);
                        _alGetBufferPtrDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, void**, void>)loadFunction(names + alGetBufferPtrDirectSOFT_offset);
                        _alGetBufferPtrvDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, void**, void>)loadFunction(names + alGetBufferPtrvDirectSOFT_offset);
                    }
                    
                    _alDeferUpdatesDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void>)loadFunction(names + alDeferUpdatesDirectSOFT_offset);
                    _alProcessUpdatesDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void>)loadFunction(names + alProcessUpdatesDirectSOFT_offset);
                    
                    var alEventCallbackDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, delegate* unmanaged[Cdecl]<All, uint, uint, nuint, byte*, void*, void>, void*, void>)loadFunction(names + alEventCallbackDirectSOFT_offset);
                    _alEventCallbackDirectSOFT_fnptr = alEventCallbackDirectSOFT_fnptr;
                    if (alEventCallbackDirectSOFT_fnptr is not null)
                    {
                        _alEventControlDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, byte, void>)loadFunction(names + alEventControlDirectSOFT_offset);
                        _alGetPointerDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void*>)loadFunction(names + alGetPointerDirectSOFT_offset);
                        _alGetPointervDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void**, void>)loadFunction(names + alGetPointervDirectSOFT_offset);
                    }
                    
                    var alGetSource3dDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, double*, double*, double*, void>)loadFunction(names + alGetSource3dDirectSOFT_offset);
                    _alGetSource3dDirectSOFT_fnptr = alGetSource3dDirectSOFT_fnptr;
                    if (alGetSource3dDirectSOFT_fnptr is not null)
                    {
                        _alGetSource3i64DirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, long*, long*, long*, void>)loadFunction(names + alGetSource3i64DirectSOFT_offset);
                        _alGetSourcedDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, double*, void>)loadFunction(names + alGetSourcedDirectSOFT_offset);
                        _alGetSourcedvDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, double*, void>)loadFunction(names + alGetSourcedvDirectSOFT_offset);
                        _alGetSourcei64DirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, long*, void>)loadFunction(names + alGetSourcei64DirectSOFT_offset);
                        _alGetSourcei64vDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, long*, void>)loadFunction(names + alGetSourcei64vDirectSOFT_offset);
                        _alSource3dDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, double, double, double, void>)loadFunction(names + alSource3dDirectSOFT_offset);
                        _alSource3i64DirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, long, long, long, void>)loadFunction(names + alSource3i64DirectSOFT_offset);
                        _alSourcedDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, double, void>)loadFunction(names + alSourcedDirectSOFT_offset);
                        _alSourcedvDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, double*, void>)loadFunction(names + alSourcedvDirectSOFT_offset);
                        _alSourcei64DirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, long, void>)loadFunction(names + alSourcei64DirectSOFT_offset);
                        _alSourcei64vDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, long*, void>)loadFunction(names + alSourcei64vDirectSOFT_offset);
                    }
                    
                    _alGetStringiDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, byte*>)loadFunction(names + alGetStringiDirectSOFT_offset);
                    
                    _alSourcePlayAtTimeDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, long, void>)loadFunction(names + alSourcePlayAtTimeDirectSOFT_offset);
                    _alSourcePlayAtTimevDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, long, void>)loadFunction(names + alSourcePlayAtTimevDirectSOFT_offset);
                    
                    var alAuxiliaryEffectSlotfDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float, void>)loadFunction(names + alAuxiliaryEffectSlotfDirect_offset);
                    _alAuxiliaryEffectSlotfDirect_fnptr = alAuxiliaryEffectSlotfDirect_fnptr;
                    if (alAuxiliaryEffectSlotfDirect_fnptr is not null)
                    {
                        _alAuxiliaryEffectSlotfvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunction(names + alAuxiliaryEffectSlotfvDirect_offset);
                        _alAuxiliaryEffectSlotiDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, void>)loadFunction(names + alAuxiliaryEffectSlotiDirect_offset);
                        _alAuxiliaryEffectSlotivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunction(names + alAuxiliaryEffectSlotivDirect_offset);
                        _alDeleteAuxiliaryEffectSlotsDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunction(names + alDeleteAuxiliaryEffectSlotsDirect_offset);
                        _alDeleteEffectsDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunction(names + alDeleteEffectsDirect_offset);
                        _alDeleteFiltersDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunction(names + alDeleteFiltersDirect_offset);
                        _alEffectfDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float, void>)loadFunction(names + alEffectfDirect_offset);
                        _alEffectfvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunction(names + alEffectfvDirect_offset);
                        _alEffectiDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, void>)loadFunction(names + alEffectiDirect_offset);
                        _alEffectivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunction(names + alEffectivDirect_offset);
                        _alFilterfDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float, void>)loadFunction(names + alFilterfDirect_offset);
                        _alFilterfvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunction(names + alFilterfvDirect_offset);
                        _alFilteriDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, void>)loadFunction(names + alFilteriDirect_offset);
                        _alFilterivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunction(names + alFilterivDirect_offset);
                        _alGenAuxiliaryEffectSlotsDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunction(names + alGenAuxiliaryEffectSlotsDirect_offset);
                        _alGenEffectsDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunction(names + alGenEffectsDirect_offset);
                        _alGenFiltersDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunction(names + alGenFiltersDirect_offset);
                        _alGetAuxiliaryEffectSlotfDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunction(names + alGetAuxiliaryEffectSlotfDirect_offset);
                        _alGetAuxiliaryEffectSlotfvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunction(names + alGetAuxiliaryEffectSlotfvDirect_offset);
                        _alGetAuxiliaryEffectSlotiDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunction(names + alGetAuxiliaryEffectSlotiDirect_offset);
                        _alGetAuxiliaryEffectSlotivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunction(names + alGetAuxiliaryEffectSlotivDirect_offset);
                        _alGetEffectfDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunction(names + alGetEffectfDirect_offset);
                        _alGetEffectfvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunction(names + alGetEffectfvDirect_offset);
                        _alGetEffectiDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunction(names + alGetEffectiDirect_offset);
                        _alGetEffectivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunction(names + alGetEffectivDirect_offset);
                        _alGetFilterfDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunction(names + alGetFilterfDirect_offset);
                        _alGetFilterfvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunction(names + alGetFilterfvDirect_offset);
                        _alGetFilteriDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunction(names + alGetFilteriDirect_offset);
                        _alGetFilterivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunction(names + alGetFilterivDirect_offset);
                        _alIsAuxiliaryEffectSlotDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void>)loadFunction(names + alIsAuxiliaryEffectSlotDirect_offset);
                        _alIsEffectDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, byte>)loadFunction(names + alIsEffectDirect_offset);
                        _alIsFilterDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void>)loadFunction(names + alIsFilterDirect_offset);
                    }
                    
                    _alMacOSXGetRenderChannelCountDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int>)loadFunction(names + alMacOSXGetRenderChannelCountDirect_offset);
                    _alMacOSXRenderChannelCountDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void>)loadFunction(names + alMacOSXRenderChannelCountDirect_offset);
                    
                    _EAXGetDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, Guid*, uint, uint, void*, uint, int>)loadFunction(names + EAXGetDirect_offset);
                    _EAXSetDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, Guid*, uint, uint, void*, uint, int>)loadFunction(names + EAXSetDirect_offset);
                    
                    _EAXGetBufferModeDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, int>)loadFunction(names + EAXGetBufferModeDirect_offset);
                    _EAXSetBufferModeDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, int, byte>)loadFunction(names + EAXSetBufferModeDirect_offset);
                }
            }
        }
    }
}
