// <auto-generated />
// This file is auto generated, do not edit.
#nullable enable
using System;
using System.Buffers;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using OpenTK.Core.Native;
using OpenTK.Mathematics;
using OpenTK.Audio;

namespace OpenTK.Audio.OpenAL
{
    public unsafe partial struct ALPointers
    {
        /// <summary>Loads all function pointers via specified loader function.</summary>
        internal static void InitializePointers(delegate* unmanaged[Cdecl]<byte*, void*> loadFunction, ALPointers* pointers)
        {
            fixed (byte* names = AllFunctionNames)
            {
                var initializePointersInternal_fnptr = (delegate* unmanaged[Cdecl]<delegate* unmanaged[Cdecl]<byte*, void*>, byte*, ALPointers*, void>)&InitializePointersInternal;
                initializePointersInternal_fnptr(loadFunction, names, pointers);
            }
        }
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void InitializePointersInternal(delegate* unmanaged[Cdecl]<byte*, void*> loadFunction, byte* names, ALPointers* pointers)
        {
            var loadFunctionSuppressed = (delegate* unmanaged[Cdecl, SuppressGCTransition]<byte*, void*>)loadFunction;
            
            var alBuffer3f_fnptr = (delegate* unmanaged[Cdecl]<int, int, float, float, float, void>)loadFunctionSuppressed(names + alBuffer3f_offset);
            pointers->_alBuffer3f_fnptr = alBuffer3f_fnptr;
            if (alBuffer3f_fnptr is not null)
            {
                pointers->_alBuffer3i_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, int, int, void>)loadFunctionSuppressed(names + alBuffer3i_offset);
                pointers->_alBufferData_fnptr = (delegate* unmanaged[Cdecl]<int, int, void*, int, int, void>)loadFunctionSuppressed(names + alBufferData_offset);
                pointers->_alBufferf_fnptr = (delegate* unmanaged[Cdecl]<int, int, float, void>)loadFunctionSuppressed(names + alBufferf_offset);
                pointers->_alBufferfv_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunctionSuppressed(names + alBufferfv_offset);
                pointers->_alBufferi_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, void>)loadFunctionSuppressed(names + alBufferi_offset);
                pointers->_alBufferiv_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunctionSuppressed(names + alBufferiv_offset);
                pointers->_alDeleteBuffers_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunctionSuppressed(names + alDeleteBuffers_offset);
                pointers->_alDeleteSources_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunctionSuppressed(names + alDeleteSources_offset);
                pointers->_alDisable_fnptr = (delegate* unmanaged[Cdecl]<int, void>)loadFunctionSuppressed(names + alDisable_offset);
                pointers->_alDistanceModel_fnptr = (delegate* unmanaged[Cdecl]<int, void>)loadFunctionSuppressed(names + alDistanceModel_offset);
                pointers->_alDopperFactor_fnptr = (delegate* unmanaged[Cdecl]<float, void>)loadFunctionSuppressed(names + alDopperFactor_offset);
                pointers->_alEnable_fnptr = (delegate* unmanaged[Cdecl]<int, void>)loadFunctionSuppressed(names + alEnable_offset);
                pointers->_alGenBuffers_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunctionSuppressed(names + alGenBuffers_offset);
                pointers->_alGenSources_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunctionSuppressed(names + alGenSources_offset);
                pointers->_alGetBoolean_fnptr = (delegate* unmanaged[Cdecl]<int, byte>)loadFunctionSuppressed(names + alGetBoolean_offset);
                pointers->_alGetBooleanv_fnptr = (delegate* unmanaged[Cdecl]<int, byte*, void>)loadFunctionSuppressed(names + alGetBooleanv_offset);
                pointers->_alGetBuffer3f_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, float*, float*, void>)loadFunctionSuppressed(names + alGetBuffer3f_offset);
                pointers->_alGetBuffer3i_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, int*, int*, void>)loadFunctionSuppressed(names + alGetBuffer3i_offset);
                pointers->_alGetBufferf_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunctionSuppressed(names + alGetBufferf_offset);
                pointers->_alGetBufferfv_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunctionSuppressed(names + alGetBufferfv_offset);
                pointers->_alGetBufferi_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunctionSuppressed(names + alGetBufferi_offset);
                pointers->_alGetBufferiv_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunctionSuppressed(names + alGetBufferiv_offset);
                pointers->_alGetDouble_fnptr = (delegate* unmanaged[Cdecl]<int, double>)loadFunctionSuppressed(names + alGetDouble_offset);
                pointers->_alGetDoublev_fnptr = (delegate* unmanaged[Cdecl]<int, double*, void>)loadFunctionSuppressed(names + alGetDoublev_offset);
                pointers->_alGetEnumValue_fnptr = (delegate* unmanaged[Cdecl]<byte*, int>)loadFunctionSuppressed(names + alGetEnumValue_offset);
                pointers->_alGetError_fnptr = (delegate* unmanaged[Cdecl]<int>)loadFunctionSuppressed(names + alGetError_offset);
                pointers->_alGetFloat_fnptr = (delegate* unmanaged[Cdecl]<int, float>)loadFunctionSuppressed(names + alGetFloat_offset);
                pointers->_alGetFloatv_fnptr = (delegate* unmanaged[Cdecl]<int, float*, void>)loadFunctionSuppressed(names + alGetFloatv_offset);
                pointers->_alGetInteger_fnptr = (delegate* unmanaged[Cdecl]<int, int>)loadFunctionSuppressed(names + alGetInteger_offset);
                pointers->_alGetIntegerv_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunctionSuppressed(names + alGetIntegerv_offset);
                pointers->_alGetListener3f_fnptr = (delegate* unmanaged[Cdecl]<int, float*, float*, float*, void>)loadFunctionSuppressed(names + alGetListener3f_offset);
                pointers->_alGetListener3i_fnptr = (delegate* unmanaged[Cdecl]<int, int*, int*, int*, void>)loadFunctionSuppressed(names + alGetListener3i_offset);
                pointers->_alGetListenerf_fnptr = (delegate* unmanaged[Cdecl]<int, float*, void>)loadFunctionSuppressed(names + alGetListenerf_offset);
                pointers->_alGetListenerfv_fnptr = (delegate* unmanaged[Cdecl]<int, float*, void>)loadFunctionSuppressed(names + alGetListenerfv_offset);
                pointers->_alGetListeneri_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunctionSuppressed(names + alGetListeneri_offset);
                pointers->_alGetListeneriv_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunctionSuppressed(names + alGetListeneriv_offset);
                pointers->_alGetProcAddress_fnptr = (delegate* unmanaged[Cdecl]<byte*, void*>)loadFunctionSuppressed(names + alGetProcAddress_offset);
                pointers->_alGetSource3f_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, float*, float*, void>)loadFunctionSuppressed(names + alGetSource3f_offset);
                pointers->_alGetSource3i_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, int*, int*, void>)loadFunctionSuppressed(names + alGetSource3i_offset);
                pointers->_alGetSourcef_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunctionSuppressed(names + alGetSourcef_offset);
                pointers->_alGetSourcefv_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunctionSuppressed(names + alGetSourcefv_offset);
                pointers->_alGetSourcei_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunctionSuppressed(names + alGetSourcei_offset);
                pointers->_alGetSourceiv_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunctionSuppressed(names + alGetSourceiv_offset);
                pointers->_alGetString_fnptr = (delegate* unmanaged[Cdecl]<int, byte*>)loadFunctionSuppressed(names + alGetString_offset);
                pointers->_alIsBuffer_fnptr = (delegate* unmanaged[Cdecl]<int, byte>)loadFunctionSuppressed(names + alIsBuffer_offset);
                pointers->_alIsEnabled_fnptr = (delegate* unmanaged[Cdecl]<int, byte>)loadFunctionSuppressed(names + alIsEnabled_offset);
                pointers->_alIsExtensionPresent_fnptr = (delegate* unmanaged[Cdecl]<byte*, byte>)loadFunctionSuppressed(names + alIsExtensionPresent_offset);
                pointers->_alIsSource_fnptr = (delegate* unmanaged[Cdecl]<int, byte>)loadFunctionSuppressed(names + alIsSource_offset);
                pointers->_alListener3f_fnptr = (delegate* unmanaged[Cdecl]<int, float, float, float, void>)loadFunctionSuppressed(names + alListener3f_offset);
                pointers->_alListener3i_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, int, void>)loadFunctionSuppressed(names + alListener3i_offset);
                pointers->_alListenerf_fnptr = (delegate* unmanaged[Cdecl]<int, float, void>)loadFunctionSuppressed(names + alListenerf_offset);
                pointers->_alListenerfv_fnptr = (delegate* unmanaged[Cdecl]<int, float*, void>)loadFunctionSuppressed(names + alListenerfv_offset);
                pointers->_alListeneri_fnptr = (delegate* unmanaged[Cdecl]<int, int, void>)loadFunctionSuppressed(names + alListeneri_offset);
                pointers->_alListeneriv_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunctionSuppressed(names + alListeneriv_offset);
                pointers->_alSource3f_fnptr = (delegate* unmanaged[Cdecl]<int, int, float, float, float, void>)loadFunctionSuppressed(names + alSource3f_offset);
                pointers->_alSource3i_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, int, int, void>)loadFunctionSuppressed(names + alSource3i_offset);
                pointers->_alSourcef_fnptr = (delegate* unmanaged[Cdecl]<int, int, float, void>)loadFunctionSuppressed(names + alSourcef_offset);
                pointers->_alSourcefv_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunctionSuppressed(names + alSourcefv_offset);
                pointers->_alSourcei_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, void>)loadFunctionSuppressed(names + alSourcei_offset);
                pointers->_alSourceiv_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunctionSuppressed(names + alSourceiv_offset);
                pointers->_alSourcePause_fnptr = (delegate* unmanaged[Cdecl]<int, void>)loadFunctionSuppressed(names + alSourcePause_offset);
                pointers->_alSourcePausev_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunctionSuppressed(names + alSourcePausev_offset);
                pointers->_alSourcePlay_fnptr = (delegate* unmanaged[Cdecl]<int, void>)loadFunctionSuppressed(names + alSourcePlay_offset);
                pointers->_alSourcePlayv_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunctionSuppressed(names + alSourcePlayv_offset);
                pointers->_alSourceQueueBuffers_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunctionSuppressed(names + alSourceQueueBuffers_offset);
                pointers->_alSourceRewind_fnptr = (delegate* unmanaged[Cdecl]<int, void>)loadFunctionSuppressed(names + alSourceRewind_offset);
                pointers->_alSourceRewindv_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunctionSuppressed(names + alSourceRewindv_offset);
                pointers->_alSourceStop_fnptr = (delegate* unmanaged[Cdecl]<int, void>)loadFunctionSuppressed(names + alSourceStop_offset);
                pointers->_alSourceStopv_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunctionSuppressed(names + alSourceStopv_offset);
                pointers->_alSourceUnqueueBuffers_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunctionSuppressed(names + alSourceUnqueueBuffers_offset);
                pointers->_alSpeedOfSound_fnptr = (delegate* unmanaged[Cdecl]<float, void>)loadFunctionSuppressed(names + alSpeedOfSound_offset);
            }
            
            pointers->_EAXGet_fnptr = (delegate* unmanaged[Cdecl]<Guid*, uint, uint, void*, uint, int>)loadFunctionSuppressed(names + EAXGet_offset);
            pointers->_EAXSet_fnptr = (delegate* unmanaged[Cdecl]<Guid*, uint, uint, void*, uint, int>)loadFunctionSuppressed(names + EAXSet_offset);
            
            pointers->_EAXGetBufferMode_fnptr = (delegate* unmanaged[Cdecl]<int, int*, int>)loadFunctionSuppressed(names + EAXGetBufferMode_offset);
            pointers->_EAXSetBufferMode_fnptr = (delegate* unmanaged[Cdecl]<int, int*, int, byte>)loadFunctionSuppressed(names + EAXSetBufferMode_offset);
            
            var alAuxiliaryEffectSlotf_fnptr = (delegate* unmanaged[Cdecl]<int, int, float, void>)loadFunctionSuppressed(names + alAuxiliaryEffectSlotf_offset);
            pointers->_alAuxiliaryEffectSlotf_fnptr = alAuxiliaryEffectSlotf_fnptr;
            if (alAuxiliaryEffectSlotf_fnptr is not null)
            {
                pointers->_alAuxiliaryEffectSlotfv_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunctionSuppressed(names + alAuxiliaryEffectSlotfv_offset);
                pointers->_alAuxiliaryEffectSloti_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, void>)loadFunctionSuppressed(names + alAuxiliaryEffectSloti_offset);
                pointers->_alAuxiliaryEffectSlotiv_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunctionSuppressed(names + alAuxiliaryEffectSlotiv_offset);
                pointers->_alDeleteAuxiliaryEffectSlots_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunctionSuppressed(names + alDeleteAuxiliaryEffectSlots_offset);
                pointers->_alDeleteEffects_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunctionSuppressed(names + alDeleteEffects_offset);
                pointers->_alDeleteFilters_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunctionSuppressed(names + alDeleteFilters_offset);
                pointers->_alEffectf_fnptr = (delegate* unmanaged[Cdecl]<int, int, float, void>)loadFunctionSuppressed(names + alEffectf_offset);
                pointers->_alEffectfv_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunctionSuppressed(names + alEffectfv_offset);
                pointers->_alEffecti_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, void>)loadFunctionSuppressed(names + alEffecti_offset);
                pointers->_alEffectiv_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunctionSuppressed(names + alEffectiv_offset);
                pointers->_alFilterf_fnptr = (delegate* unmanaged[Cdecl]<int, int, float, void>)loadFunctionSuppressed(names + alFilterf_offset);
                pointers->_alFilterfv_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunctionSuppressed(names + alFilterfv_offset);
                pointers->_alFilteri_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, void>)loadFunctionSuppressed(names + alFilteri_offset);
                pointers->_alFilteriv_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunctionSuppressed(names + alFilteriv_offset);
                pointers->_alGenAuxiliaryEffectSlots_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunctionSuppressed(names + alGenAuxiliaryEffectSlots_offset);
                pointers->_alGenEffects_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunctionSuppressed(names + alGenEffects_offset);
                pointers->_alGenFilters_fnptr = (delegate* unmanaged[Cdecl]<int, int*, void>)loadFunctionSuppressed(names + alGenFilters_offset);
                pointers->_alGetAuxiliaryEffectSlotf_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunctionSuppressed(names + alGetAuxiliaryEffectSlotf_offset);
                pointers->_alGetAuxiliaryEffectSlotfv_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunctionSuppressed(names + alGetAuxiliaryEffectSlotfv_offset);
                pointers->_alGetAuxiliaryEffectSloti_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunctionSuppressed(names + alGetAuxiliaryEffectSloti_offset);
                pointers->_alGetAuxiliaryEffectSlotiv_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunctionSuppressed(names + alGetAuxiliaryEffectSlotiv_offset);
                pointers->_alGetEffectf_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunctionSuppressed(names + alGetEffectf_offset);
                pointers->_alGetEffectfv_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunctionSuppressed(names + alGetEffectfv_offset);
                pointers->_alGetEffecti_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunctionSuppressed(names + alGetEffecti_offset);
                pointers->_alGetEffectiv_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunctionSuppressed(names + alGetEffectiv_offset);
                pointers->_alGetFilterf_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunctionSuppressed(names + alGetFilterf_offset);
                pointers->_alGetFilterfv_fnptr = (delegate* unmanaged[Cdecl]<int, int, float*, void>)loadFunctionSuppressed(names + alGetFilterfv_offset);
                pointers->_alGetFilteri_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunctionSuppressed(names + alGetFilteri_offset);
                pointers->_alGetFilteriv_fnptr = (delegate* unmanaged[Cdecl]<int, int, int*, void>)loadFunctionSuppressed(names + alGetFilteriv_offset);
                pointers->_alIsAuxiliaryEffectSlot_fnptr = (delegate* unmanaged[Cdecl]<int, void>)loadFunctionSuppressed(names + alIsAuxiliaryEffectSlot_offset);
                pointers->_alIsEffect_fnptr = (delegate* unmanaged[Cdecl]<int, byte>)loadFunctionSuppressed(names + alIsEffect_offset);
                pointers->_alIsFilter_fnptr = (delegate* unmanaged[Cdecl]<int, void>)loadFunctionSuppressed(names + alIsFilter_offset);
            }
            
            var alDebugMessageCallbackEXT_fnptr = (delegate* unmanaged[Cdecl]<delegate* unmanaged[Cdecl]<All, All, uint, All, nuint, byte*, void*, int>, void*, void>)loadFunctionSuppressed(names + alDebugMessageCallbackEXT_offset);
            pointers->_alDebugMessageCallbackEXT_fnptr = alDebugMessageCallbackEXT_fnptr;
            if (alDebugMessageCallbackEXT_fnptr is not null)
            {
                pointers->_alDebugMessageControlEXT_fnptr = (delegate* unmanaged[Cdecl]<int, int, uint, int, uint*, byte, void>)loadFunctionSuppressed(names + alDebugMessageControlEXT_offset);
                pointers->_alDebugMessageInsertEXT_fnptr = (delegate* unmanaged[Cdecl]<int, int, uint, int, byte*, void>)loadFunctionSuppressed(names + alDebugMessageInsertEXT_offset);
                pointers->_alGetDebugMessageLogEXT_fnptr = (delegate* unmanaged[Cdecl]<uint, int, int*, int*, uint*, int*, int*, byte*, uint>)loadFunctionSuppressed(names + alGetDebugMessageLogEXT_offset);
                pointers->_alGetObjectLabelEXT_fnptr = (delegate* unmanaged[Cdecl]<int, uint, int, int*, byte*, void>)loadFunctionSuppressed(names + alGetObjectLabelEXT_offset);
                pointers->_alGetPointerEXT_fnptr = (delegate* unmanaged[Cdecl]<int, void*>)loadFunctionSuppressed(names + alGetPointerEXT_offset);
                pointers->_alGetPointervEXT_fnptr = (delegate* unmanaged[Cdecl]<int, void**, void>)loadFunctionSuppressed(names + alGetPointervEXT_offset);
                pointers->_alObjectLabelEXT_fnptr = (delegate* unmanaged[Cdecl]<int, uint, int, byte*, void>)loadFunctionSuppressed(names + alObjectLabelEXT_offset);
                pointers->_alPopDebugGroupEXT_fnptr = (delegate* unmanaged[Cdecl]<void>)loadFunctionSuppressed(names + alPopDebugGroupEXT_offset);
                pointers->_alPushDebugGroupEXT_fnptr = (delegate* unmanaged[Cdecl]<int, uint, int, byte*, void>)loadFunctionSuppressed(names + alPushDebugGroupEXT_offset);
            }
            
            pointers->_alMacOSXGetRenderChannelCount_fnptr = (delegate* unmanaged[Cdecl]<int>)loadFunctionSuppressed(names + alMacOSXGetRenderChannelCount_offset);
            pointers->_alMacOSXRenderChannelCount_fnptr = (delegate* unmanaged[Cdecl]<int, void>)loadFunctionSuppressed(names + alMacOSXRenderChannelCount_offset);
            
            pointers->_alRequestFoldbackStart_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, float*, delegate* unmanaged[Cdecl]<All, nuint, void>, void>)loadFunctionSuppressed(names + alRequestFoldbackStart_offset);
            pointers->_alRequestFoldbackStop_fnptr = (delegate* unmanaged[Cdecl]<void>)loadFunctionSuppressed(names + alRequestFoldbackStop_offset);
            
            pointers->_alSourceAddNotification_fnptr = (delegate* unmanaged[Cdecl]<int, uint, delegate* unmanaged[Cdecl]<uint, uint, void*, void>, void*, int>)loadFunctionSuppressed(names + alSourceAddNotification_offset);
            pointers->_alSourceRemoveNotification_fnptr = (delegate* unmanaged[Cdecl]<int, uint, delegate* unmanaged[Cdecl]<uint, uint, void*, void>, void*, void>)loadFunctionSuppressed(names + alSourceRemoveNotification_offset);
            
            pointers->_alSourceGetRenderingQuality_fnptr = (delegate* unmanaged[Cdecl]<int, int>)loadFunctionSuppressed(names + alSourceGetRenderingQuality_offset);
            pointers->_alSourceRenderingQuality_fnptr = (delegate* unmanaged[Cdecl]<int, int, void>)loadFunctionSuppressed(names + alSourceRenderingQuality_offset);
            
            pointers->_AttenuationScale_LOKI_fnptr = (delegate* unmanaged[Cdecl]<float, void>)loadFunctionSuppressed(names + AttenuationScale_LOKI_offset);
            
            pointers->_BufferDataWithCallback_LOKI_fnptr = (delegate* unmanaged[Cdecl]<int, delegate* unmanaged[Cdecl]<uint, uint, void*, All, uint, int>, void>)loadFunctionSuppressed(names + BufferDataWithCallback_LOKI_offset);
            
            var alBufferCallbackSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, delegate* unmanaged[Cdecl]<void*, void*, nuint, nuint>, void*, void>)loadFunctionSuppressed(names + alBufferCallbackSOFT_offset);
            pointers->_alBufferCallbackSOFT_fnptr = alBufferCallbackSOFT_fnptr;
            if (alBufferCallbackSOFT_fnptr is not null)
            {
                pointers->_alGetBuffer3PtrSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, void**, void**, void**, void>)loadFunctionSuppressed(names + alGetBuffer3PtrSOFT_offset);
                pointers->_alGetBufferPtrSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, void**, void>)loadFunctionSuppressed(names + alGetBufferPtrSOFT_offset);
                pointers->_alGetBufferPtrvSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, void**, void>)loadFunctionSuppressed(names + alGetBufferPtrvSOFT_offset);
            }
            
            var alBufferSamplesSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, uint, int, int, int, int, void*, void>)loadFunctionSuppressed(names + alBufferSamplesSOFT_offset);
            pointers->_alBufferSamplesSOFT_fnptr = alBufferSamplesSOFT_fnptr;
            if (alBufferSamplesSOFT_fnptr is not null)
            {
                pointers->_alBufferSubSamplesSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, int, int, void*, void>)loadFunctionSuppressed(names + alBufferSubSamplesSOFT_offset);
                pointers->_alGetBufferSamplesSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, int, int, int, void*, void>)loadFunctionSuppressed(names + alGetBufferSamplesSOFT_offset);
                pointers->_alIsBufferFormatSupportedSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, byte>)loadFunctionSuppressed(names + alIsBufferFormatSupportedSOFT_offset);
            }
            
            pointers->_alBufferSubDataSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, void*, int, int, void>)loadFunctionSuppressed(names + alBufferSubDataSOFT_offset);
            
            pointers->_alDeferUpdatesSOFT_fnptr = (delegate* unmanaged[Cdecl]<void>)loadFunctionSuppressed(names + alDeferUpdatesSOFT_offset);
            pointers->_alProcessUpdatesSOFT_fnptr = (delegate* unmanaged[Cdecl]<void>)loadFunctionSuppressed(names + alProcessUpdatesSOFT_offset);
            
            var alEventCallbackSOFT_fnptr = (delegate* unmanaged[Cdecl]<delegate* unmanaged[Cdecl]<All, uint, uint, nuint, byte*, void*, void>, void*, void>)loadFunctionSuppressed(names + alEventCallbackSOFT_offset);
            pointers->_alEventCallbackSOFT_fnptr = alEventCallbackSOFT_fnptr;
            if (alEventCallbackSOFT_fnptr is not null)
            {
                pointers->_alEventControlSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int*, byte, void>)loadFunctionSuppressed(names + alEventControlSOFT_offset);
                pointers->_alGetPointerSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, void*>)loadFunctionSuppressed(names + alGetPointerSOFT_offset);
                pointers->_alGetPointervSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, void**, void>)loadFunctionSuppressed(names + alGetPointervSOFT_offset);
            }
            
            var alGetSource3dSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, double*, double*, double*, void>)loadFunctionSuppressed(names + alGetSource3dSOFT_offset);
            pointers->_alGetSource3dSOFT_fnptr = alGetSource3dSOFT_fnptr;
            if (alGetSource3dSOFT_fnptr is not null)
            {
                pointers->_alGetSource3i64SOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, long*, long*, long*, void>)loadFunctionSuppressed(names + alGetSource3i64SOFT_offset);
                pointers->_alGetSourcedSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, double*, void>)loadFunctionSuppressed(names + alGetSourcedSOFT_offset);
                pointers->_alGetSourcedvSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, double*, void>)loadFunctionSuppressed(names + alGetSourcedvSOFT_offset);
                pointers->_alGetSourcei64SOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, long*, void>)loadFunctionSuppressed(names + alGetSourcei64SOFT_offset);
                pointers->_alGetSourcei64vSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, long*, void>)loadFunctionSuppressed(names + alGetSourcei64vSOFT_offset);
                pointers->_alSource3dSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, double, double, double, void>)loadFunctionSuppressed(names + alSource3dSOFT_offset);
                pointers->_alSource3i64SOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, long, long, long, void>)loadFunctionSuppressed(names + alSource3i64SOFT_offset);
                pointers->_alSourcedSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, double, void>)loadFunctionSuppressed(names + alSourcedSOFT_offset);
                pointers->_alSourcedvSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, double*, void>)loadFunctionSuppressed(names + alSourcedvSOFT_offset);
                pointers->_alSourcei64SOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, long, void>)loadFunctionSuppressed(names + alSourcei64SOFT_offset);
                pointers->_alSourcei64vSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, long*, void>)loadFunctionSuppressed(names + alSourcei64vSOFT_offset);
            }
            
            pointers->_alGetStringiSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, byte*>)loadFunctionSuppressed(names + alGetStringiSOFT_offset);
            
            pointers->_alSourcePlayAtTimeSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, long, void>)loadFunctionSuppressed(names + alSourcePlayAtTimeSOFT_offset);
            pointers->_alSourcePlayAtTimevSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int*, long, void>)loadFunctionSuppressed(names + alSourcePlayAtTimevSOFT_offset);
            
            var alBuffer3fDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float, float, float, void>)loadFunctionSuppressed(names + alBuffer3fDirect_offset);
            pointers->_alBuffer3fDirect_fnptr = alBuffer3fDirect_fnptr;
            if (alBuffer3fDirect_fnptr is not null)
            {
                pointers->_alBuffer3iDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, int, int, void>)loadFunctionSuppressed(names + alBuffer3iDirect_offset);
                pointers->_alBufferDataDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, void*, int, int, void>)loadFunctionSuppressed(names + alBufferDataDirect_offset);
                pointers->_alBufferfDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float, void>)loadFunctionSuppressed(names + alBufferfDirect_offset);
                pointers->_alBufferfvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunctionSuppressed(names + alBufferfvDirect_offset);
                pointers->_alBufferiDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, void>)loadFunctionSuppressed(names + alBufferiDirect_offset);
                pointers->_alBufferivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunctionSuppressed(names + alBufferivDirect_offset);
                pointers->_alDeleteBuffersDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunctionSuppressed(names + alDeleteBuffersDirect_offset);
                pointers->_alDeleteSourcesDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunctionSuppressed(names + alDeleteSourcesDirect_offset);
                pointers->_alDisableDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void>)loadFunctionSuppressed(names + alDisableDirect_offset);
                pointers->_alDistanceModelDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void>)loadFunctionSuppressed(names + alDistanceModelDirect_offset);
                pointers->_alDopperFactorDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, float, void>)loadFunctionSuppressed(names + alDopperFactorDirect_offset);
                pointers->_alEnableDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void>)loadFunctionSuppressed(names + alEnableDirect_offset);
                pointers->_alGenBuffersDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunctionSuppressed(names + alGenBuffersDirect_offset);
                pointers->_alGenSourcesDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunctionSuppressed(names + alGenSourcesDirect_offset);
                pointers->_alGetBooleanDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, byte>)loadFunctionSuppressed(names + alGetBooleanDirect_offset);
                pointers->_alGetBooleanvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, byte*, void>)loadFunctionSuppressed(names + alGetBooleanvDirect_offset);
                pointers->_alGetBuffer3fDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, float*, float*, void>)loadFunctionSuppressed(names + alGetBuffer3fDirect_offset);
                pointers->_alGetBuffer3iDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, int*, int*, void>)loadFunctionSuppressed(names + alGetBuffer3iDirect_offset);
                pointers->_alGetBufferfDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunctionSuppressed(names + alGetBufferfDirect_offset);
                pointers->_alGetBufferfvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunctionSuppressed(names + alGetBufferfvDirect_offset);
                pointers->_alGetBufferiDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunctionSuppressed(names + alGetBufferiDirect_offset);
                pointers->_alGetBufferivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunctionSuppressed(names + alGetBufferivDirect_offset);
                pointers->_alGetDoubleDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, double>)loadFunctionSuppressed(names + alGetDoubleDirect_offset);
                pointers->_alGetDoublevDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, double*, void>)loadFunctionSuppressed(names + alGetDoublevDirect_offset);
                pointers->_alGetEnumValueDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte*, int>)loadFunctionSuppressed(names + alGetEnumValueDirect_offset);
                pointers->_alGetErrorDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int>)loadFunctionSuppressed(names + alGetErrorDirect_offset);
                pointers->_alGetFloatDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, float>)loadFunctionSuppressed(names + alGetFloatDirect_offset);
                pointers->_alGetFloatvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, float*, void>)loadFunctionSuppressed(names + alGetFloatvDirect_offset);
                pointers->_alGetIntegerDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int>)loadFunctionSuppressed(names + alGetIntegerDirect_offset);
                pointers->_alGetIntegervDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunctionSuppressed(names + alGetIntegervDirect_offset);
                pointers->_alGetListener3fDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, float*, float*, float*, void>)loadFunctionSuppressed(names + alGetListener3fDirect_offset);
                pointers->_alGetListener3iDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, int*, int*, void>)loadFunctionSuppressed(names + alGetListener3iDirect_offset);
                pointers->_alGetListenerfDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, float*, void>)loadFunctionSuppressed(names + alGetListenerfDirect_offset);
                pointers->_alGetListenerfvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, float*, void>)loadFunctionSuppressed(names + alGetListenerfvDirect_offset);
                pointers->_alGetListeneriDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunctionSuppressed(names + alGetListeneriDirect_offset);
                pointers->_alGetListenerivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunctionSuppressed(names + alGetListenerivDirect_offset);
                pointers->_alGetProcAddressDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte*, void*>)loadFunctionSuppressed(names + alGetProcAddressDirect_offset);
                pointers->_alGetSource3fDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, float*, float*, void>)loadFunctionSuppressed(names + alGetSource3fDirect_offset);
                pointers->_alGetSource3iDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, int*, int*, void>)loadFunctionSuppressed(names + alGetSource3iDirect_offset);
                pointers->_alGetSourcefDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunctionSuppressed(names + alGetSourcefDirect_offset);
                pointers->_alGetSourcefvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunctionSuppressed(names + alGetSourcefvDirect_offset);
                pointers->_alGetSourceiDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunctionSuppressed(names + alGetSourceiDirect_offset);
                pointers->_alGetSourceivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunctionSuppressed(names + alGetSourceivDirect_offset);
                pointers->_alGetStringDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, byte*>)loadFunctionSuppressed(names + alGetStringDirect_offset);
                pointers->_alIsBufferDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, byte>)loadFunctionSuppressed(names + alIsBufferDirect_offset);
                pointers->_alIsEnabledDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, byte>)loadFunctionSuppressed(names + alIsEnabledDirect_offset);
                pointers->_alIsExtensionPresentDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte*, byte>)loadFunctionSuppressed(names + alIsExtensionPresentDirect_offset);
                pointers->_alIsSourceDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, byte>)loadFunctionSuppressed(names + alIsSourceDirect_offset);
                pointers->_alListener3fDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, float, float, float, void>)loadFunctionSuppressed(names + alListener3fDirect_offset);
                pointers->_alListener3iDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, int, void>)loadFunctionSuppressed(names + alListener3iDirect_offset);
                pointers->_alListenerfDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, float, void>)loadFunctionSuppressed(names + alListenerfDirect_offset);
                pointers->_alListenerfvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, float*, void>)loadFunctionSuppressed(names + alListenerfvDirect_offset);
                pointers->_alListeneriDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, void>)loadFunctionSuppressed(names + alListeneriDirect_offset);
                pointers->_alListenerivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunctionSuppressed(names + alListenerivDirect_offset);
                pointers->_alSource3fDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float, float, float, void>)loadFunctionSuppressed(names + alSource3fDirect_offset);
                pointers->_alSource3iDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, int, int, void>)loadFunctionSuppressed(names + alSource3iDirect_offset);
                pointers->_alSourcefDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float, void>)loadFunctionSuppressed(names + alSourcefDirect_offset);
                pointers->_alSourcefvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunctionSuppressed(names + alSourcefvDirect_offset);
                pointers->_alSourceiDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, void>)loadFunctionSuppressed(names + alSourceiDirect_offset);
                pointers->_alSourceivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunctionSuppressed(names + alSourceivDirect_offset);
                pointers->_alSourcePauseDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void>)loadFunctionSuppressed(names + alSourcePauseDirect_offset);
                pointers->_alSourcePausevDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunctionSuppressed(names + alSourcePausevDirect_offset);
                pointers->_alSourcePlayDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void>)loadFunctionSuppressed(names + alSourcePlayDirect_offset);
                pointers->_alSourcePlayvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunctionSuppressed(names + alSourcePlayvDirect_offset);
                pointers->_alSourceQueueBuffersDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunctionSuppressed(names + alSourceQueueBuffersDirect_offset);
                pointers->_alSourceRewindDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void>)loadFunctionSuppressed(names + alSourceRewindDirect_offset);
                pointers->_alSourceRewindvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunctionSuppressed(names + alSourceRewindvDirect_offset);
                pointers->_alSourceStopDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void>)loadFunctionSuppressed(names + alSourceStopDirect_offset);
                pointers->_alSourceStopvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunctionSuppressed(names + alSourceStopvDirect_offset);
                pointers->_alSourceUnqueueBuffersDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunctionSuppressed(names + alSourceUnqueueBuffersDirect_offset);
                pointers->_alSpeedOfSoundDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, float, void>)loadFunctionSuppressed(names + alSpeedOfSoundDirect_offset);
                
                var alDebugMessageCallbackDirectEXT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, delegate* unmanaged[Cdecl]<All, All, uint, All, nuint, byte*, void*, int>, void*, void>)loadFunctionSuppressed(names + alDebugMessageCallbackDirectEXT_offset);
                pointers->_alDebugMessageCallbackDirectEXT_fnptr = alDebugMessageCallbackDirectEXT_fnptr;
                if (alDebugMessageCallbackDirectEXT_fnptr is not null)
                {
                    pointers->_alDebugMessageControlDirectEXT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, uint, int, uint*, byte, void>)loadFunctionSuppressed(names + alDebugMessageControlDirectEXT_offset);
                    pointers->_alDebugMessageInsertDirectEXT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, uint, int, byte*, void>)loadFunctionSuppressed(names + alDebugMessageInsertDirectEXT_offset);
                    pointers->_alGetDebugMessageLogDirectEXT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, uint, int, int*, int*, uint*, int*, int*, byte*, uint>)loadFunctionSuppressed(names + alGetDebugMessageLogDirectEXT_offset);
                    pointers->_alGetObjectLabelDirectEXT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, uint, int, int*, byte*, void>)loadFunctionSuppressed(names + alGetObjectLabelDirectEXT_offset);
                    pointers->_alGetPointerDirectEXT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void*>)loadFunctionSuppressed(names + alGetPointerDirectEXT_offset);
                    pointers->_alGetPointervDirectEXT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void**, void>)loadFunctionSuppressed(names + alGetPointervDirectEXT_offset);
                    pointers->_alObjectLabelDirectEXT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, uint, int, byte*, void>)loadFunctionSuppressed(names + alObjectLabelDirectEXT_offset);
                    pointers->_alPopDebugGroupDirectEXT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void>)loadFunctionSuppressed(names + alPopDebugGroupDirectEXT_offset);
                    pointers->_alPushDebugGroupDirectEXT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, uint, int, byte*, void>)loadFunctionSuppressed(names + alPushDebugGroupDirectEXT_offset);
                }
                
                pointers->_alRequestFoldbackStartDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, float*, delegate* unmanaged[Cdecl]<All, nuint, void>, void>)loadFunctionSuppressed(names + alRequestFoldbackStartDirect_offset);
                pointers->_alRequestFoldbackStopDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void>)loadFunctionSuppressed(names + alRequestFoldbackStopDirect_offset);
                
                pointers->_alSourceAddNotificationDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, uint, delegate* unmanaged[Cdecl]<uint, uint, void*, void>, void*, int>)loadFunctionSuppressed(names + alSourceAddNotificationDirect_offset);
                pointers->_alSourceRemoveNotificationDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, uint, delegate* unmanaged[Cdecl]<uint, uint, void*, void>, void*, void>)loadFunctionSuppressed(names + alSourceRemoveNotificationDirect_offset);
                
                pointers->_alSourceGetRenderingQualityDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int>)loadFunctionSuppressed(names + alSourceGetRenderingQualityDirect_offset);
                pointers->_alSourceRenderingQualityDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, void>)loadFunctionSuppressed(names + alSourceRenderingQualityDirect_offset);
                
                pointers->_AttenuationScale_DirectLOKI_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, float, void>)loadFunctionSuppressed(names + AttenuationScale_DirectLOKI_offset);
                
                pointers->_BufferDataWithCallback_DirectLOKI_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, delegate* unmanaged[Cdecl]<uint, uint, void*, All, uint, int>, void>)loadFunctionSuppressed(names + BufferDataWithCallback_DirectLOKI_offset);
                
                var alBufferSamplesDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, uint, int, int, int, int, void*, void>)loadFunctionSuppressed(names + alBufferSamplesDirectSOFT_offset);
                pointers->_alBufferSamplesDirectSOFT_fnptr = alBufferSamplesDirectSOFT_fnptr;
                if (alBufferSamplesDirectSOFT_fnptr is not null)
                {
                    pointers->_alBufferSubSamplesDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, int, int, void*, void>)loadFunctionSuppressed(names + alBufferSubSamplesDirectSOFT_offset);
                    pointers->_alGetBufferSamplesDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, int, int, void*, void>)loadFunctionSuppressed(names + alGetBufferSamplesDirectSOFT_offset);
                    pointers->_alIsBufferFormatSupportedDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, byte>)loadFunctionSuppressed(names + alIsBufferFormatSupportedDirectSOFT_offset);
                }
                
                pointers->_alBufferSubDataDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, void*, int, int, void>)loadFunctionSuppressed(names + alBufferSubDataDirectSOFT_offset);
                
                var alBufferCallbackDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, delegate* unmanaged[Cdecl]<void*, void*, nuint, nuint>, void*, void>)loadFunctionSuppressed(names + alBufferCallbackDirectSOFT_offset);
                pointers->_alBufferCallbackDirectSOFT_fnptr = alBufferCallbackDirectSOFT_fnptr;
                if (alBufferCallbackDirectSOFT_fnptr is not null)
                {
                    pointers->_alGetBuffer3PtrDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, void**, void**, void**, void>)loadFunctionSuppressed(names + alGetBuffer3PtrDirectSOFT_offset);
                    pointers->_alGetBufferPtrDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, void**, void>)loadFunctionSuppressed(names + alGetBufferPtrDirectSOFT_offset);
                    pointers->_alGetBufferPtrvDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, void**, void>)loadFunctionSuppressed(names + alGetBufferPtrvDirectSOFT_offset);
                }
                
                pointers->_alDeferUpdatesDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void>)loadFunctionSuppressed(names + alDeferUpdatesDirectSOFT_offset);
                pointers->_alProcessUpdatesDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void>)loadFunctionSuppressed(names + alProcessUpdatesDirectSOFT_offset);
                
                var alEventCallbackDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, delegate* unmanaged[Cdecl]<All, uint, uint, nuint, byte*, void*, void>, void*, void>)loadFunctionSuppressed(names + alEventCallbackDirectSOFT_offset);
                pointers->_alEventCallbackDirectSOFT_fnptr = alEventCallbackDirectSOFT_fnptr;
                if (alEventCallbackDirectSOFT_fnptr is not null)
                {
                    pointers->_alEventControlDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, byte, void>)loadFunctionSuppressed(names + alEventControlDirectSOFT_offset);
                    pointers->_alGetPointerDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void*>)loadFunctionSuppressed(names + alGetPointerDirectSOFT_offset);
                    pointers->_alGetPointervDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void**, void>)loadFunctionSuppressed(names + alGetPointervDirectSOFT_offset);
                }
                
                var alGetSource3dDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, double*, double*, double*, void>)loadFunctionSuppressed(names + alGetSource3dDirectSOFT_offset);
                pointers->_alGetSource3dDirectSOFT_fnptr = alGetSource3dDirectSOFT_fnptr;
                if (alGetSource3dDirectSOFT_fnptr is not null)
                {
                    pointers->_alGetSource3i64DirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, long*, long*, long*, void>)loadFunctionSuppressed(names + alGetSource3i64DirectSOFT_offset);
                    pointers->_alGetSourcedDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, double*, void>)loadFunctionSuppressed(names + alGetSourcedDirectSOFT_offset);
                    pointers->_alGetSourcedvDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, double*, void>)loadFunctionSuppressed(names + alGetSourcedvDirectSOFT_offset);
                    pointers->_alGetSourcei64DirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, long*, void>)loadFunctionSuppressed(names + alGetSourcei64DirectSOFT_offset);
                    pointers->_alGetSourcei64vDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, long*, void>)loadFunctionSuppressed(names + alGetSourcei64vDirectSOFT_offset);
                    pointers->_alSource3dDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, double, double, double, void>)loadFunctionSuppressed(names + alSource3dDirectSOFT_offset);
                    pointers->_alSource3i64DirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, long, long, long, void>)loadFunctionSuppressed(names + alSource3i64DirectSOFT_offset);
                    pointers->_alSourcedDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, double, void>)loadFunctionSuppressed(names + alSourcedDirectSOFT_offset);
                    pointers->_alSourcedvDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, double*, void>)loadFunctionSuppressed(names + alSourcedvDirectSOFT_offset);
                    pointers->_alSourcei64DirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, long, void>)loadFunctionSuppressed(names + alSourcei64DirectSOFT_offset);
                    pointers->_alSourcei64vDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, long*, void>)loadFunctionSuppressed(names + alSourcei64vDirectSOFT_offset);
                }
                
                pointers->_alGetStringiDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, byte*>)loadFunctionSuppressed(names + alGetStringiDirectSOFT_offset);
                
                pointers->_alSourcePlayAtTimeDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, long, void>)loadFunctionSuppressed(names + alSourcePlayAtTimeDirectSOFT_offset);
                pointers->_alSourcePlayAtTimevDirectSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, long, void>)loadFunctionSuppressed(names + alSourcePlayAtTimevDirectSOFT_offset);
                
                var alAuxiliaryEffectSlotfDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float, void>)loadFunctionSuppressed(names + alAuxiliaryEffectSlotfDirect_offset);
                pointers->_alAuxiliaryEffectSlotfDirect_fnptr = alAuxiliaryEffectSlotfDirect_fnptr;
                if (alAuxiliaryEffectSlotfDirect_fnptr is not null)
                {
                    pointers->_alAuxiliaryEffectSlotfvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunctionSuppressed(names + alAuxiliaryEffectSlotfvDirect_offset);
                    pointers->_alAuxiliaryEffectSlotiDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, void>)loadFunctionSuppressed(names + alAuxiliaryEffectSlotiDirect_offset);
                    pointers->_alAuxiliaryEffectSlotivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunctionSuppressed(names + alAuxiliaryEffectSlotivDirect_offset);
                    pointers->_alDeleteAuxiliaryEffectSlotsDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunctionSuppressed(names + alDeleteAuxiliaryEffectSlotsDirect_offset);
                    pointers->_alDeleteEffectsDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunctionSuppressed(names + alDeleteEffectsDirect_offset);
                    pointers->_alDeleteFiltersDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunctionSuppressed(names + alDeleteFiltersDirect_offset);
                    pointers->_alEffectfDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float, void>)loadFunctionSuppressed(names + alEffectfDirect_offset);
                    pointers->_alEffectfvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunctionSuppressed(names + alEffectfvDirect_offset);
                    pointers->_alEffectiDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, void>)loadFunctionSuppressed(names + alEffectiDirect_offset);
                    pointers->_alEffectivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunctionSuppressed(names + alEffectivDirect_offset);
                    pointers->_alFilterfDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float, void>)loadFunctionSuppressed(names + alFilterfDirect_offset);
                    pointers->_alFilterfvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunctionSuppressed(names + alFilterfvDirect_offset);
                    pointers->_alFilteriDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, void>)loadFunctionSuppressed(names + alFilteriDirect_offset);
                    pointers->_alFilterivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunctionSuppressed(names + alFilterivDirect_offset);
                    pointers->_alGenAuxiliaryEffectSlotsDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunctionSuppressed(names + alGenAuxiliaryEffectSlotsDirect_offset);
                    pointers->_alGenEffectsDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunctionSuppressed(names + alGenEffectsDirect_offset);
                    pointers->_alGenFiltersDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, void>)loadFunctionSuppressed(names + alGenFiltersDirect_offset);
                    pointers->_alGetAuxiliaryEffectSlotfDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunctionSuppressed(names + alGetAuxiliaryEffectSlotfDirect_offset);
                    pointers->_alGetAuxiliaryEffectSlotfvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunctionSuppressed(names + alGetAuxiliaryEffectSlotfvDirect_offset);
                    pointers->_alGetAuxiliaryEffectSlotiDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunctionSuppressed(names + alGetAuxiliaryEffectSlotiDirect_offset);
                    pointers->_alGetAuxiliaryEffectSlotivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunctionSuppressed(names + alGetAuxiliaryEffectSlotivDirect_offset);
                    pointers->_alGetEffectfDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunctionSuppressed(names + alGetEffectfDirect_offset);
                    pointers->_alGetEffectfvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunctionSuppressed(names + alGetEffectfvDirect_offset);
                    pointers->_alGetEffectiDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunctionSuppressed(names + alGetEffectiDirect_offset);
                    pointers->_alGetEffectivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunctionSuppressed(names + alGetEffectivDirect_offset);
                    pointers->_alGetFilterfDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunctionSuppressed(names + alGetFilterfDirect_offset);
                    pointers->_alGetFilterfvDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, float*, void>)loadFunctionSuppressed(names + alGetFilterfvDirect_offset);
                    pointers->_alGetFilteriDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunctionSuppressed(names + alGetFilteriDirect_offset);
                    pointers->_alGetFilterivDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunctionSuppressed(names + alGetFilterivDirect_offset);
                    pointers->_alIsAuxiliaryEffectSlotDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void>)loadFunctionSuppressed(names + alIsAuxiliaryEffectSlotDirect_offset);
                    pointers->_alIsEffectDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, byte>)loadFunctionSuppressed(names + alIsEffectDirect_offset);
                    pointers->_alIsFilterDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void>)loadFunctionSuppressed(names + alIsFilterDirect_offset);
                }
                
                pointers->_alMacOSXGetRenderChannelCountDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int>)loadFunctionSuppressed(names + alMacOSXGetRenderChannelCountDirect_offset);
                pointers->_alMacOSXRenderChannelCountDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, void>)loadFunctionSuppressed(names + alMacOSXRenderChannelCountDirect_offset);
                
                pointers->_EAXGetDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, Guid*, uint, uint, void*, uint, int>)loadFunctionSuppressed(names + EAXGetDirect_offset);
                pointers->_EAXSetDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, Guid*, uint, uint, void*, uint, int>)loadFunctionSuppressed(names + EAXSetDirect_offset);
                
                pointers->_EAXGetBufferModeDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, int>)loadFunctionSuppressed(names + EAXGetBufferModeDirect_offset);
                pointers->_EAXSetBufferModeDirect_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int*, int, byte>)loadFunctionSuppressed(names + EAXSetBufferModeDirect_offset);
            }
        }
    }
}
