// <auto-generated />
// This file is auto generated, do not edit.
#nullable enable
using System;
using System.Buffers;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using OpenTK.Core.Native;
using OpenTK.Mathematics;
using OpenTK.Audio;

namespace OpenTK.Audio.OpenAL.ALC
{
    public unsafe partial struct ALCPointers
    {
        internal static ReadOnlySpan<byte> AllFunctionNames => "alcCaptureCloseDevice\0alcCaptureOpenDevice\0alcCaptureSamples\0alcCaptureStart\0alcCaptureStop\0alcCloseDevice\0alcCreateContext\0alcDestroyContext\0alcGetContextsDevice\0alcGetCurrentContext\0alcGetEnumValue\0alcGetError\0alcGetIntegerv\0alcGetProcAddress\0alcGetString\0alcIsExtensionPresent\0alcMakeContextCurrent\0alcOpenDevice\0alcProcessContext\0alcSuspendContext\0alcGetProcAddress2\0alcASAGetListener\0alcASAGetSource\0alcASASetListener\0alcASASetSource\0alcGetThreadContext\0alcSetThreadContext\0alcMacOSXGetMixerMaxiumumBusses\0alcMacOSXGetMixerOutputRate\0alcMacOSXGetRenderingQuality\0alcMacOSXMixerMaxiumumBusses\0alcMacOSXMixerOutputRate\0alcMacOSXRenderingQuality\0alcOutputCapturerAvailableSamples\0alcOutputCapturerPrepare\0alcOutputCapturerSamples\0alcOutputCapturerStart\0alcOutputCapturerStop\0GetAudioChannel_LOKI\0SetAudioChannel_LOKI\0alcDevicePauseSOFT\0alcDeviceResumeSOFT\0alcEventCallbackSOFT\0alcEventControlSOFT\0alcEventIsSupportedSOFT\0alcGetInteger64vSOFT\0alcGetStringiSOFT\0alcIsRenderFormatSupportedSOFT\0alcLoopbackOpenDeviceSOFT\0alcRenderSamplesSOFT\0alcReopenDeviceSOFT\0alcResetDeviceSOFT\0"u8;
        internal const ushort alcCaptureCloseDevice_offset = 0;
        internal const ushort alcCaptureOpenDevice_offset = 22;
        internal const ushort alcCaptureSamples_offset = 43;
        internal const ushort alcCaptureStart_offset = 61;
        internal const ushort alcCaptureStop_offset = 77;
        internal const ushort alcCloseDevice_offset = 92;
        internal const ushort alcCreateContext_offset = 107;
        internal const ushort alcDestroyContext_offset = 124;
        internal const ushort alcGetContextsDevice_offset = 142;
        internal const ushort alcGetCurrentContext_offset = 163;
        internal const ushort alcGetEnumValue_offset = 184;
        internal const ushort alcGetError_offset = 200;
        internal const ushort alcGetIntegerv_offset = 212;
        internal const ushort alcGetProcAddress_offset = 227;
        internal const ushort alcGetString_offset = 245;
        internal const ushort alcIsExtensionPresent_offset = 258;
        internal const ushort alcMakeContextCurrent_offset = 280;
        internal const ushort alcOpenDevice_offset = 302;
        internal const ushort alcProcessContext_offset = 316;
        internal const ushort alcSuspendContext_offset = 334;
        internal const ushort alcGetProcAddress2_offset = 352;
        internal const ushort alcASAGetListener_offset = 371;
        internal const ushort alcASAGetSource_offset = 389;
        internal const ushort alcASASetListener_offset = 405;
        internal const ushort alcASASetSource_offset = 423;
        internal const ushort alcGetThreadContext_offset = 439;
        internal const ushort alcSetThreadContext_offset = 459;
        internal const ushort alcMacOSXGetMixerMaxiumumBusses_offset = 479;
        internal const ushort alcMacOSXGetMixerOutputRate_offset = 511;
        internal const ushort alcMacOSXGetRenderingQuality_offset = 539;
        internal const ushort alcMacOSXMixerMaxiumumBusses_offset = 568;
        internal const ushort alcMacOSXMixerOutputRate_offset = 597;
        internal const ushort alcMacOSXRenderingQuality_offset = 622;
        internal const ushort alcOutputCapturerAvailableSamples_offset = 648;
        internal const ushort alcOutputCapturerPrepare_offset = 682;
        internal const ushort alcOutputCapturerSamples_offset = 707;
        internal const ushort alcOutputCapturerStart_offset = 732;
        internal const ushort alcOutputCapturerStop_offset = 755;
        internal const ushort GetAudioChannel_LOKI_offset = 777;
        internal const ushort SetAudioChannel_LOKI_offset = 798;
        internal const ushort alcDevicePauseSOFT_offset = 819;
        internal const ushort alcDeviceResumeSOFT_offset = 838;
        internal const ushort alcEventCallbackSOFT_offset = 858;
        internal const ushort alcEventControlSOFT_offset = 879;
        internal const ushort alcEventIsSupportedSOFT_offset = 899;
        internal const ushort alcGetInteger64vSOFT_offset = 923;
        internal const ushort alcGetStringiSOFT_offset = 944;
        internal const ushort alcIsRenderFormatSupportedSOFT_offset = 962;
        internal const ushort alcLoopbackOpenDeviceSOFT_offset = 993;
        internal const ushort alcRenderSamplesSOFT_offset = 1019;
        internal const ushort alcReopenDeviceSOFT_offset = 1040;
        internal const ushort alcResetDeviceSOFT_offset = 1060;
    }
}
