// <auto-generated />
// This file is auto generated, do not edit.
#nullable enable
using System;
using System.Buffers;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using OpenTK.Core.Native;
using OpenTK.Mathematics;
using OpenTK.Audio;

namespace OpenTK.Audio.OpenAL.ALC
{
    public unsafe partial struct ALCPointers
    {
        internal static ReadOnlySpan<byte> AllFunctionNames => "alcASAGetListener\0alcASAGetSource\0alcASASetListener\0alcASASetSource\0alcCaptureCloseDevice\0alcCaptureOpenDevice\0alcCaptureSamples\0alcCaptureStart\0alcCaptureStop\0alcCloseDevice\0alcCreateContext\0alcDestroyContext\0alcDevicePauseSOFT\0alcDeviceResumeSOFT\0alcEventCallbackSOFT\0alcEventControlSOFT\0alcEventIsSupportedSOFT\0alcGetContextsDevice\0alcGetCurrentContext\0alcGetEnumValue\0alcGetError\0alcGetInteger64vSOFT\0alcGetIntegerv\0alcGetProcAddress\0alcGetProcAddress2\0alcGetString\0alcGetStringiSOFT\0alcGetThreadContext\0alcIsExtensionPresent\0alcIsRenderFormatSupportedSOFT\0alcLoopbackOpenDeviceSOFT\0alcMacOSXGetMixerMaxiumumBusses\0alcMacOSXGetMixerOutputRate\0alcMacOSXGetRenderingQuality\0alcMacOSXMixerMaxiumumBusses\0alcMacOSXMixerOutputRate\0alcMacOSXRenderingQuality\0alcMakeContextCurrent\0alcOpenDevice\0alcOutputCapturerAvailableSamples\0alcOutputCapturerPrepare\0alcOutputCapturerSamples\0alcOutputCapturerStart\0alcOutputCapturerStop\0alcProcessContext\0alcRenderSamplesSOFT\0alcReopenDeviceSOFT\0alcResetDeviceSOFT\0alcSetThreadContext\0alcSuspendContext\0GetAudioChannel_LOKI\0SetAudioChannel_LOKI\0"u8;
        internal const ushort alcASAGetListener_offset = 0;
        internal const ushort alcASAGetSource_offset = 18;
        internal const ushort alcASASetListener_offset = 34;
        internal const ushort alcASASetSource_offset = 52;
        internal const ushort alcCaptureCloseDevice_offset = 68;
        internal const ushort alcCaptureOpenDevice_offset = 90;
        internal const ushort alcCaptureSamples_offset = 111;
        internal const ushort alcCaptureStart_offset = 129;
        internal const ushort alcCaptureStop_offset = 145;
        internal const ushort alcCloseDevice_offset = 160;
        internal const ushort alcCreateContext_offset = 175;
        internal const ushort alcDestroyContext_offset = 192;
        internal const ushort alcDevicePauseSOFT_offset = 210;
        internal const ushort alcDeviceResumeSOFT_offset = 229;
        internal const ushort alcEventCallbackSOFT_offset = 249;
        internal const ushort alcEventControlSOFT_offset = 270;
        internal const ushort alcEventIsSupportedSOFT_offset = 290;
        internal const ushort alcGetContextsDevice_offset = 314;
        internal const ushort alcGetCurrentContext_offset = 335;
        internal const ushort alcGetEnumValue_offset = 356;
        internal const ushort alcGetError_offset = 372;
        internal const ushort alcGetInteger64vSOFT_offset = 384;
        internal const ushort alcGetIntegerv_offset = 405;
        internal const ushort alcGetProcAddress_offset = 420;
        internal const ushort alcGetProcAddress2_offset = 438;
        internal const ushort alcGetString_offset = 457;
        internal const ushort alcGetStringiSOFT_offset = 470;
        internal const ushort alcGetThreadContext_offset = 488;
        internal const ushort alcIsExtensionPresent_offset = 508;
        internal const ushort alcIsRenderFormatSupportedSOFT_offset = 530;
        internal const ushort alcLoopbackOpenDeviceSOFT_offset = 561;
        internal const ushort alcMacOSXGetMixerMaxiumumBusses_offset = 587;
        internal const ushort alcMacOSXGetMixerOutputRate_offset = 619;
        internal const ushort alcMacOSXGetRenderingQuality_offset = 647;
        internal const ushort alcMacOSXMixerMaxiumumBusses_offset = 676;
        internal const ushort alcMacOSXMixerOutputRate_offset = 705;
        internal const ushort alcMacOSXRenderingQuality_offset = 730;
        internal const ushort alcMakeContextCurrent_offset = 756;
        internal const ushort alcOpenDevice_offset = 778;
        internal const ushort alcOutputCapturerAvailableSamples_offset = 792;
        internal const ushort alcOutputCapturerPrepare_offset = 826;
        internal const ushort alcOutputCapturerSamples_offset = 851;
        internal const ushort alcOutputCapturerStart_offset = 876;
        internal const ushort alcOutputCapturerStop_offset = 899;
        internal const ushort alcProcessContext_offset = 921;
        internal const ushort alcRenderSamplesSOFT_offset = 939;
        internal const ushort alcReopenDeviceSOFT_offset = 960;
        internal const ushort alcResetDeviceSOFT_offset = 980;
        internal const ushort alcSetThreadContext_offset = 999;
        internal const ushort alcSuspendContext_offset = 1019;
        internal const ushort GetAudioChannel_LOKI_offset = 1037;
        internal const ushort SetAudioChannel_LOKI_offset = 1058;
    }
}
