// <auto-generated />
// This file is auto generated, do not edit.
#nullable enable
using System;
using System.Buffers;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using OpenTK.Audio;
using OpenTK.Core.Native;
using OpenTK.Mathematics;

namespace OpenTK.Audio.OpenAL.ALC
{
    public readonly unsafe partial struct ALCPointers
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ALCPointers"/> struct.
        /// </summary>
        internal ALCPointers(delegate* unmanaged[Cdecl]<IntPtr, byte*, void*> loadFunction, IntPtr device)
        {
            fixed (byte* names = AllFunctionNames)
            {
                
                var alcCaptureCloseDevice_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte>)loadFunction(device, names + alcCaptureCloseDevice_offset);
                _alcCaptureCloseDevice_fnptr = alcCaptureCloseDevice_fnptr;
                if (alcCaptureCloseDevice_fnptr is not null)
                {
                    _alcCaptureOpenDevice_fnptr = (delegate* unmanaged[Cdecl]<byte*, uint, int, int, IntPtr>)loadFunction(device, names + alcCaptureOpenDevice_offset);
                    _alcCaptureSamples_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void*, int, void>)loadFunction(device, names + alcCaptureSamples_offset);
                    _alcCaptureStart_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void>)loadFunction(device, names + alcCaptureStart_offset);
                    _alcCaptureStop_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void>)loadFunction(device, names + alcCaptureStop_offset);
                }
                
                var alcCloseDevice_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte>)loadFunction(device, names + alcCloseDevice_offset);
                _alcCloseDevice_fnptr = alcCloseDevice_fnptr;
                if (alcCloseDevice_fnptr is not null)
                {
                    _alcCreateContext_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int*, IntPtr>)loadFunction(device, names + alcCreateContext_offset);
                    _alcDestroyContext_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void>)loadFunction(device, names + alcDestroyContext_offset);
                    _alcGetContextsDevice_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, IntPtr>)loadFunction(device, names + alcGetContextsDevice_offset);
                    _alcGetCurrentContext_fnptr = (delegate* unmanaged[Cdecl]<IntPtr>)loadFunction(device, names + alcGetCurrentContext_offset);
                    _alcGetEnumValue_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte*, int>)loadFunction(device, names + alcGetEnumValue_offset);
                    _alcGetError_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int>)loadFunction(device, names + alcGetError_offset);
                    _alcGetIntegerv_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)loadFunction(device, names + alcGetIntegerv_offset);
                    _alcGetProcAddress_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte*, void*>)loadFunction(device, names + alcGetProcAddress_offset);
                    _alcGetString_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, byte*>)loadFunction(device, names + alcGetString_offset);
                    _alcIsExtensionPresent_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte*, byte>)loadFunction(device, names + alcIsExtensionPresent_offset);
                    _alcMakeContextCurrent_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte>)loadFunction(device, names + alcMakeContextCurrent_offset);
                    _alcOpenDevice_fnptr = (delegate* unmanaged[Cdecl]<byte*, IntPtr>)loadFunction(device, names + alcOpenDevice_offset);
                    _alcProcessContext_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void>)loadFunction(device, names + alcProcessContext_offset);
                    _alcSuspendContext_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void>)loadFunction(device, names + alcSuspendContext_offset);
                }
                
                _alcGetProcAddress2_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte*, void*>)loadFunction(device, names + alcGetProcAddress2_offset);
                
                var alcASAGetListener_fnptr = (delegate* unmanaged[Cdecl]<uint, void*, uint*, int>)loadFunction(device, names + alcASAGetListener_offset);
                _alcASAGetListener_fnptr = alcASAGetListener_fnptr;
                if (alcASAGetListener_fnptr is not null)
                {
                    _alcASAGetSource_fnptr = (delegate* unmanaged[Cdecl]<uint, uint, void*, uint*, int>)loadFunction(device, names + alcASAGetSource_offset);
                    _alcASASetListener_fnptr = (delegate* unmanaged[Cdecl]<uint, void*, uint, int>)loadFunction(device, names + alcASASetListener_offset);
                    _alcASASetSource_fnptr = (delegate* unmanaged[Cdecl]<uint, uint, void*, uint, int>)loadFunction(device, names + alcASASetSource_offset);
                }
                
                
                _alcGetThreadContext_fnptr = (delegate* unmanaged[Cdecl]<IntPtr>)loadFunction(device, names + alcGetThreadContext_offset);
                _alcSetThreadContext_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte>)loadFunction(device, names + alcSetThreadContext_offset);
                
                var alcMacOSXGetMixerMaxiumumBusses_fnptr = (delegate* unmanaged[Cdecl]<int>)loadFunction(device, names + alcMacOSXGetMixerMaxiumumBusses_offset);
                _alcMacOSXGetMixerMaxiumumBusses_fnptr = alcMacOSXGetMixerMaxiumumBusses_fnptr;
                if (alcMacOSXGetMixerMaxiumumBusses_fnptr is not null)
                {
                    _alcMacOSXGetMixerOutputRate_fnptr = (delegate* unmanaged[Cdecl]<double>)loadFunction(device, names + alcMacOSXGetMixerOutputRate_offset);
                    _alcMacOSXGetRenderingQuality_fnptr = (delegate* unmanaged[Cdecl]<int>)loadFunction(device, names + alcMacOSXGetRenderingQuality_offset);
                    _alcMacOSXMixerMaxiumumBusses_fnptr = (delegate* unmanaged[Cdecl]<int, void>)loadFunction(device, names + alcMacOSXMixerMaxiumumBusses_offset);
                    _alcMacOSXMixerOutputRate_fnptr = (delegate* unmanaged[Cdecl]<double, void>)loadFunction(device, names + alcMacOSXMixerOutputRate_offset);
                    _alcMacOSXRenderingQuality_fnptr = (delegate* unmanaged[Cdecl]<int, void>)loadFunction(device, names + alcMacOSXRenderingQuality_offset);
                }
                
                var alcOutputCapturerAvailableSamples_fnptr = (delegate* unmanaged[Cdecl]<void>)loadFunction(device, names + alcOutputCapturerAvailableSamples_offset);
                _alcOutputCapturerAvailableSamples_fnptr = alcOutputCapturerAvailableSamples_fnptr;
                if (alcOutputCapturerAvailableSamples_fnptr is not null)
                {
                    _alcOutputCapturerPrepare_fnptr = (delegate* unmanaged[Cdecl]<uint, int, int, void>)loadFunction(device, names + alcOutputCapturerPrepare_offset);
                    _alcOutputCapturerSamples_fnptr = (delegate* unmanaged[Cdecl]<void*, int, void>)loadFunction(device, names + alcOutputCapturerSamples_offset);
                    _alcOutputCapturerStart_fnptr = (delegate* unmanaged[Cdecl]<void>)loadFunction(device, names + alcOutputCapturerStart_offset);
                    _alcOutputCapturerStop_fnptr = (delegate* unmanaged[Cdecl]<void>)loadFunction(device, names + alcOutputCapturerStop_offset);
                }
                
                _GetAudioChannel_LOKI_fnptr = (delegate* unmanaged[Cdecl]<uint, float>)loadFunction(device, names + GetAudioChannel_LOKI_offset);
                _SetAudioChannel_LOKI_fnptr = (delegate* unmanaged[Cdecl]<uint, float, void>)loadFunction(device, names + SetAudioChannel_LOKI_offset);
                
                _alcDevicePauseSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void>)loadFunction(device, names + alcDevicePauseSOFT_offset);
                _alcDeviceResumeSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void>)loadFunction(device, names + alcDeviceResumeSOFT_offset);
                
                _alcEventCallbackSOFT_fnptr = (delegate* unmanaged[Cdecl]<delegate* unmanaged[Cdecl]<All, All, ALCDevice, nuint, byte*, void*, void>, void*, void>)loadFunction(device, names + alcEventCallbackSOFT_offset);
                _alcEventControlSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int*, byte, byte>)loadFunction(device, names + alcEventControlSOFT_offset);
                _alcEventIsSupportedSOFT_fnptr = (delegate* unmanaged[Cdecl]<int, int, int>)loadFunction(device, names + alcEventIsSupportedSOFT_offset);
                
                _alcGetInteger64vSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, long*, void>)loadFunction(device, names + alcGetInteger64vSOFT_offset);
                
                _alcGetStringiSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, byte*>)loadFunction(device, names + alcGetStringiSOFT_offset);
                
                _alcIsRenderFormatSupportedSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, byte>)loadFunction(device, names + alcIsRenderFormatSupportedSOFT_offset);
                _alcLoopbackOpenDeviceSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, IntPtr>)loadFunction(device, names + alcLoopbackOpenDeviceSOFT_offset);
                _alcRenderSamplesSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void*, int, void>)loadFunction(device, names + alcRenderSamplesSOFT_offset);
                
                _alcReopenDeviceSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte*, int*, byte>)loadFunction(device, names + alcReopenDeviceSOFT_offset);
                
                _alcResetDeviceSOFT_fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int*, byte>)loadFunction(device, names + alcResetDeviceSOFT_offset);
            }
        }
    }
}
