// <auto-generated />
// This file is auto generated, do not edit.
#nullable enable
using System;
using System.Buffers;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using OpenTK.Core.Native;
using OpenTK.Mathematics;
using OpenTK.Audio;

namespace OpenTK.Audio.OpenAL.ALC
{
    public unsafe partial struct ALCPointers
    {
        /// <summary>Initializes all function pointers to their lazy loader functions.</summary>
        internal static void InitializeLazyLoaders(ref ALCPointers pointers)
        {
            if (pointers._alcGetProcAddress_fnptr is null) pointers._alcGetProcAddress_fnptr = &alcGetProcAddress_Lazy;
            pointers._alcASAGetListener_fnptr = &alcASAGetListener_Lazy;
            pointers._alcASAGetSource_fnptr = &alcASAGetSource_Lazy;
            pointers._alcASASetListener_fnptr = &alcASASetListener_Lazy;
            pointers._alcASASetSource_fnptr = &alcASASetSource_Lazy;
            pointers._alcCaptureCloseDevice_fnptr = &alcCaptureCloseDevice_Lazy;
            pointers._alcCaptureOpenDevice_fnptr = &alcCaptureOpenDevice_Lazy;
            pointers._alcCaptureSamples_fnptr = &alcCaptureSamples_Lazy;
            pointers._alcCaptureStart_fnptr = &alcCaptureStart_Lazy;
            pointers._alcCaptureStop_fnptr = &alcCaptureStop_Lazy;
            pointers._alcCloseDevice_fnptr = &alcCloseDevice_Lazy;
            pointers._alcCreateContext_fnptr = &alcCreateContext_Lazy;
            pointers._alcDestroyContext_fnptr = &alcDestroyContext_Lazy;
            pointers._alcDevicePauseSOFT_fnptr = &alcDevicePauseSOFT_Lazy;
            pointers._alcDeviceResumeSOFT_fnptr = &alcDeviceResumeSOFT_Lazy;
            pointers._alcEventCallbackSOFT_fnptr = &alcEventCallbackSOFT_Lazy;
            pointers._alcEventControlSOFT_fnptr = &alcEventControlSOFT_Lazy;
            pointers._alcEventIsSupportedSOFT_fnptr = &alcEventIsSupportedSOFT_Lazy;
            pointers._alcGetContextsDevice_fnptr = &alcGetContextsDevice_Lazy;
            pointers._alcGetCurrentContext_fnptr = &alcGetCurrentContext_Lazy;
            pointers._alcGetEnumValue_fnptr = &alcGetEnumValue_Lazy;
            pointers._alcGetError_fnptr = &alcGetError_Lazy;
            pointers._alcGetInteger64vSOFT_fnptr = &alcGetInteger64vSOFT_Lazy;
            pointers._alcGetIntegerv_fnptr = &alcGetIntegerv_Lazy;
            pointers._alcGetProcAddress2_fnptr = &alcGetProcAddress2_Lazy;
            pointers._alcGetString_fnptr = &alcGetString_Lazy;
            pointers._alcGetStringiSOFT_fnptr = &alcGetStringiSOFT_Lazy;
            pointers._alcGetThreadContext_fnptr = &alcGetThreadContext_Lazy;
            pointers._alcIsExtensionPresent_fnptr = &alcIsExtensionPresent_Lazy;
            pointers._alcIsRenderFormatSupportedSOFT_fnptr = &alcIsRenderFormatSupportedSOFT_Lazy;
            pointers._alcLoopbackOpenDeviceSOFT_fnptr = &alcLoopbackOpenDeviceSOFT_Lazy;
            pointers._alcMacOSXGetMixerMaxiumumBusses_fnptr = &alcMacOSXGetMixerMaxiumumBusses_Lazy;
            pointers._alcMacOSXGetMixerOutputRate_fnptr = &alcMacOSXGetMixerOutputRate_Lazy;
            pointers._alcMacOSXGetRenderingQuality_fnptr = &alcMacOSXGetRenderingQuality_Lazy;
            pointers._alcMacOSXMixerMaxiumumBusses_fnptr = &alcMacOSXMixerMaxiumumBusses_Lazy;
            pointers._alcMacOSXMixerOutputRate_fnptr = &alcMacOSXMixerOutputRate_Lazy;
            pointers._alcMacOSXRenderingQuality_fnptr = &alcMacOSXRenderingQuality_Lazy;
            pointers._alcMakeContextCurrent_fnptr = &alcMakeContextCurrent_Lazy;
            pointers._alcOpenDevice_fnptr = &alcOpenDevice_Lazy;
            pointers._alcOutputCapturerAvailableSamples_fnptr = &alcOutputCapturerAvailableSamples_Lazy;
            pointers._alcOutputCapturerPrepare_fnptr = &alcOutputCapturerPrepare_Lazy;
            pointers._alcOutputCapturerSamples_fnptr = &alcOutputCapturerSamples_Lazy;
            pointers._alcOutputCapturerStart_fnptr = &alcOutputCapturerStart_Lazy;
            pointers._alcOutputCapturerStop_fnptr = &alcOutputCapturerStop_Lazy;
            pointers._alcProcessContext_fnptr = &alcProcessContext_Lazy;
            pointers._alcRenderSamplesSOFT_fnptr = &alcRenderSamplesSOFT_Lazy;
            pointers._alcReopenDeviceSOFT_fnptr = &alcReopenDeviceSOFT_Lazy;
            pointers._alcResetDeviceSOFT_fnptr = &alcResetDeviceSOFT_Lazy;
            pointers._alcSetThreadContext_fnptr = &alcSetThreadContext_Lazy;
            pointers._alcSuspendContext_fnptr = &alcSuspendContext_Lazy;
            pointers._GetAudioChannel_LOKI_fnptr = &GetAudioChannel_LOKI_Lazy;
            pointers._SetAudioChannel_LOKI_fnptr = &SetAudioChannel_LOKI_Lazy;
        }
    }
}
