// <auto-generated />
// This file is auto generated, do not edit.
#nullable enable
using System;
using System.Buffers;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using OpenTK.Audio;
using OpenTK.Core.Native;
using OpenTK.Mathematics;

namespace OpenTK.Audio.OpenAL.ALC
{
    public unsafe partial struct ALCPointers
    {
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static int alcASAGetListener_Lazy(uint property, void* data, uint* dataSize)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<uint, void*, uint*, int>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcASAGetListener_offset));
            ALLoader.Default.ALC._pointers->_alcASAGetListener_fnptr = fnptr;
            return fnptr(property, data, dataSize);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static int alcASAGetSource_Lazy(uint property, uint source, void* data, uint* dataSize)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<uint, uint, void*, uint*, int>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcASAGetSource_offset));
            ALLoader.Default.ALC._pointers->_alcASAGetSource_fnptr = fnptr;
            return fnptr(property, source, data, dataSize);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static int alcASASetListener_Lazy(uint property, void* data, uint dataSize)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<uint, void*, uint, int>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcASASetListener_offset));
            ALLoader.Default.ALC._pointers->_alcASASetListener_fnptr = fnptr;
            return fnptr(property, data, dataSize);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static int alcASASetSource_Lazy(uint property, uint source, void* data, uint dataSize)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<uint, uint, void*, uint, int>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcASASetSource_offset));
            ALLoader.Default.ALC._pointers->_alcASASetSource_fnptr = fnptr;
            return fnptr(property, source, data, dataSize);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static byte alcCaptureCloseDevice_Lazy(IntPtr device)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcCaptureCloseDevice_offset));
            ALLoader.Default.ALC._pointers->_alcCaptureCloseDevice_fnptr = fnptr;
            return fnptr(device);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static IntPtr alcCaptureOpenDevice_Lazy(byte* devicename, uint frequency, int format, int buffersize)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<byte*, uint, int, int, IntPtr>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcCaptureOpenDevice_offset));
            ALLoader.Default.ALC._pointers->_alcCaptureOpenDevice_fnptr = fnptr;
            return fnptr(devicename, frequency, format, buffersize);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void alcCaptureSamples_Lazy(IntPtr device, void* buffer, int samples)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void*, int, void>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcCaptureSamples_offset));
            ALLoader.Default.ALC._pointers->_alcCaptureSamples_fnptr = fnptr;
            fnptr(device, buffer, samples);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void alcCaptureStart_Lazy(IntPtr device)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcCaptureStart_offset));
            ALLoader.Default.ALC._pointers->_alcCaptureStart_fnptr = fnptr;
            fnptr(device);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void alcCaptureStop_Lazy(IntPtr device)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcCaptureStop_offset));
            ALLoader.Default.ALC._pointers->_alcCaptureStop_fnptr = fnptr;
            fnptr(device);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static byte alcCloseDevice_Lazy(IntPtr device)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcCloseDevice_offset));
            ALLoader.Default.ALC._pointers->_alcCloseDevice_fnptr = fnptr;
            return fnptr(device);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static IntPtr alcCreateContext_Lazy(IntPtr device, int* attrlist)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int*, IntPtr>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcCreateContext_offset));
            ALLoader.Default.ALC._pointers->_alcCreateContext_fnptr = fnptr;
            return fnptr(device, attrlist);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void alcDestroyContext_Lazy(IntPtr context)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcDestroyContext_offset));
            ALLoader.Default.ALC._pointers->_alcDestroyContext_fnptr = fnptr;
            fnptr(context);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void alcDevicePauseSOFT_Lazy(IntPtr device)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcDevicePauseSOFT_offset));
            ALLoader.Default.ALC._pointers->_alcDevicePauseSOFT_fnptr = fnptr;
            fnptr(device);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void alcDeviceResumeSOFT_Lazy(IntPtr device)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcDeviceResumeSOFT_offset));
            ALLoader.Default.ALC._pointers->_alcDeviceResumeSOFT_fnptr = fnptr;
            fnptr(device);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void alcEventCallbackSOFT_Lazy(delegate* unmanaged[Cdecl]<All, All, ALCDevice, nuint, byte*, void*, void> callback, void* userParam)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<delegate* unmanaged[Cdecl]<All, All, ALCDevice, nuint, byte*, void*, void>, void*, void>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcEventCallbackSOFT_offset));
            ALLoader.Default.ALC._pointers->_alcEventCallbackSOFT_fnptr = fnptr;
            fnptr(callback, userParam);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static byte alcEventControlSOFT_Lazy(int count, int* events, byte enable)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<int, int*, byte, byte>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcEventControlSOFT_offset));
            ALLoader.Default.ALC._pointers->_alcEventControlSOFT_fnptr = fnptr;
            return fnptr(count, events, enable);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static int alcEventIsSupportedSOFT_Lazy(int eventType, int deviceType)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<int, int, int>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcEventIsSupportedSOFT_offset));
            ALLoader.Default.ALC._pointers->_alcEventIsSupportedSOFT_fnptr = fnptr;
            return fnptr(eventType, deviceType);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static IntPtr alcGetContextsDevice_Lazy(IntPtr context)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, IntPtr>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcGetContextsDevice_offset));
            ALLoader.Default.ALC._pointers->_alcGetContextsDevice_fnptr = fnptr;
            return fnptr(context);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static IntPtr alcGetCurrentContext_Lazy()
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcGetCurrentContext_offset));
            ALLoader.Default.ALC._pointers->_alcGetCurrentContext_fnptr = fnptr;
            return fnptr();
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static int alcGetEnumValue_Lazy(IntPtr device, byte* enumname)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte*, int>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcGetEnumValue_offset));
            ALLoader.Default.ALC._pointers->_alcGetEnumValue_fnptr = fnptr;
            return fnptr(device, enumname);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static int alcGetError_Lazy(IntPtr device)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcGetError_offset));
            ALLoader.Default.ALC._pointers->_alcGetError_fnptr = fnptr;
            return fnptr(device);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void alcGetInteger64vSOFT_Lazy(IntPtr device, int pname, int size, long* values)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, long*, void>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcGetInteger64vSOFT_offset));
            ALLoader.Default.ALC._pointers->_alcGetInteger64vSOFT_fnptr = fnptr;
            fnptr(device, pname, size, values);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void alcGetIntegerv_Lazy(IntPtr device, int param, int size, int* values)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int*, void>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcGetIntegerv_offset));
            ALLoader.Default.ALC._pointers->_alcGetIntegerv_fnptr = fnptr;
            fnptr(device, param, size, values);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void* alcGetProcAddress_Lazy(IntPtr device, byte* extname)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte*, void*>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcGetProcAddress_offset));
            ALLoader.Default.ALC._pointers->_alcGetProcAddress_fnptr = fnptr;
            return fnptr(device, extname);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void* alcGetProcAddress2_Lazy(IntPtr device, byte* funcName)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte*, void*>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcGetProcAddress2_offset));
            ALLoader.Default.ALC._pointers->_alcGetProcAddress2_fnptr = fnptr;
            return fnptr(device, funcName);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static byte* alcGetString_Lazy(IntPtr device, int param)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, byte*>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcGetString_offset));
            ALLoader.Default.ALC._pointers->_alcGetString_fnptr = fnptr;
            return fnptr(device, param);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static byte* alcGetStringiSOFT_Lazy(IntPtr device, int paramName, int index)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, byte*>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcGetStringiSOFT_offset));
            ALLoader.Default.ALC._pointers->_alcGetStringiSOFT_fnptr = fnptr;
            return fnptr(device, paramName, index);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static IntPtr alcGetThreadContext_Lazy()
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcGetThreadContext_offset));
            ALLoader.Default.ALC._pointers->_alcGetThreadContext_fnptr = fnptr;
            return fnptr();
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static byte alcIsExtensionPresent_Lazy(IntPtr deviceHandle, byte* extname)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte*, byte>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcIsExtensionPresent_offset));
            ALLoader.Default.ALC._pointers->_alcIsExtensionPresent_fnptr = fnptr;
            return fnptr(deviceHandle, extname);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static byte alcIsRenderFormatSupportedSOFT_Lazy(IntPtr device, int frequency, int channels, int type)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int, int, int, byte>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcIsRenderFormatSupportedSOFT_offset));
            ALLoader.Default.ALC._pointers->_alcIsRenderFormatSupportedSOFT_fnptr = fnptr;
            return fnptr(device, frequency, channels, type);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static IntPtr alcLoopbackOpenDeviceSOFT_Lazy(IntPtr device)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, IntPtr>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcLoopbackOpenDeviceSOFT_offset));
            ALLoader.Default.ALC._pointers->_alcLoopbackOpenDeviceSOFT_fnptr = fnptr;
            return fnptr(device);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static int alcMacOSXGetMixerMaxiumumBusses_Lazy()
        {
            var fnptr = (delegate* unmanaged[Cdecl]<int>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcMacOSXGetMixerMaxiumumBusses_offset));
            ALLoader.Default.ALC._pointers->_alcMacOSXGetMixerMaxiumumBusses_fnptr = fnptr;
            return fnptr();
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static double alcMacOSXGetMixerOutputRate_Lazy()
        {
            var fnptr = (delegate* unmanaged[Cdecl]<double>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcMacOSXGetMixerOutputRate_offset));
            ALLoader.Default.ALC._pointers->_alcMacOSXGetMixerOutputRate_fnptr = fnptr;
            return fnptr();
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static int alcMacOSXGetRenderingQuality_Lazy()
        {
            var fnptr = (delegate* unmanaged[Cdecl]<int>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcMacOSXGetRenderingQuality_offset));
            ALLoader.Default.ALC._pointers->_alcMacOSXGetRenderingQuality_fnptr = fnptr;
            return fnptr();
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void alcMacOSXMixerMaxiumumBusses_Lazy(int value)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<int, void>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcMacOSXMixerMaxiumumBusses_offset));
            ALLoader.Default.ALC._pointers->_alcMacOSXMixerMaxiumumBusses_fnptr = fnptr;
            fnptr(value);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void alcMacOSXMixerOutputRate_Lazy(double value)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<double, void>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcMacOSXMixerOutputRate_offset));
            ALLoader.Default.ALC._pointers->_alcMacOSXMixerOutputRate_fnptr = fnptr;
            fnptr(value);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void alcMacOSXRenderingQuality_Lazy(int value)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<int, void>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcMacOSXRenderingQuality_offset));
            ALLoader.Default.ALC._pointers->_alcMacOSXRenderingQuality_fnptr = fnptr;
            fnptr(value);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static byte alcMakeContextCurrent_Lazy(IntPtr context)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcMakeContextCurrent_offset));
            ALLoader.Default.ALC._pointers->_alcMakeContextCurrent_fnptr = fnptr;
            return fnptr(context);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static IntPtr alcOpenDevice_Lazy(byte* devicename)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<byte*, IntPtr>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcOpenDevice_offset));
            ALLoader.Default.ALC._pointers->_alcOpenDevice_fnptr = fnptr;
            return fnptr(devicename);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void alcOutputCapturerAvailableSamples_Lazy()
        {
            var fnptr = (delegate* unmanaged[Cdecl]<void>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcOutputCapturerAvailableSamples_offset));
            ALLoader.Default.ALC._pointers->_alcOutputCapturerAvailableSamples_fnptr = fnptr;
            fnptr();
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void alcOutputCapturerPrepare_Lazy(uint frequency, int format, int maxsamplecount)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<uint, int, int, void>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcOutputCapturerPrepare_offset));
            ALLoader.Default.ALC._pointers->_alcOutputCapturerPrepare_fnptr = fnptr;
            fnptr(frequency, format, maxsamplecount);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void alcOutputCapturerSamples_Lazy(void* buffer, int maxsamplecount)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<void*, int, void>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcOutputCapturerSamples_offset));
            ALLoader.Default.ALC._pointers->_alcOutputCapturerSamples_fnptr = fnptr;
            fnptr(buffer, maxsamplecount);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void alcOutputCapturerStart_Lazy()
        {
            var fnptr = (delegate* unmanaged[Cdecl]<void>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcOutputCapturerStart_offset));
            ALLoader.Default.ALC._pointers->_alcOutputCapturerStart_fnptr = fnptr;
            fnptr();
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void alcOutputCapturerStop_Lazy()
        {
            var fnptr = (delegate* unmanaged[Cdecl]<void>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcOutputCapturerStop_offset));
            ALLoader.Default.ALC._pointers->_alcOutputCapturerStop_fnptr = fnptr;
            fnptr();
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void alcProcessContext_Lazy(IntPtr context)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcProcessContext_offset));
            ALLoader.Default.ALC._pointers->_alcProcessContext_fnptr = fnptr;
            fnptr(context);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void alcRenderSamplesSOFT_Lazy(IntPtr device, void* buffer, int samples)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void*, int, void>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcRenderSamplesSOFT_offset));
            ALLoader.Default.ALC._pointers->_alcRenderSamplesSOFT_fnptr = fnptr;
            fnptr(device, buffer, samples);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static byte alcReopenDeviceSOFT_Lazy(IntPtr device, byte* deviceName, int* attribs)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte*, int*, byte>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcReopenDeviceSOFT_offset));
            ALLoader.Default.ALC._pointers->_alcReopenDeviceSOFT_fnptr = fnptr;
            return fnptr(device, deviceName, attribs);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static byte alcResetDeviceSOFT_Lazy(IntPtr device, int* attrList)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, int*, byte>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcResetDeviceSOFT_offset));
            ALLoader.Default.ALC._pointers->_alcResetDeviceSOFT_fnptr = fnptr;
            return fnptr(device, attrList);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static byte alcSetThreadContext_Lazy(IntPtr context)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, byte>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcSetThreadContext_offset));
            ALLoader.Default.ALC._pointers->_alcSetThreadContext_fnptr = fnptr;
            return fnptr(context);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void alcSuspendContext_Lazy(IntPtr context)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<IntPtr, void>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(alcSuspendContext_offset));
            ALLoader.Default.ALC._pointers->_alcSuspendContext_fnptr = fnptr;
            fnptr(context);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static float GetAudioChannel_LOKI_Lazy(uint channel)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<uint, float>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(GetAudioChannel_LOKI_offset));
            ALLoader.Default.ALC._pointers->_GetAudioChannel_LOKI_fnptr = fnptr;
            return fnptr(channel);
        }
        
        [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
        private static void SetAudioChannel_LOKI_Lazy(uint channel, float volume)
        {
            var fnptr = (delegate* unmanaged[Cdecl]<uint, float, void>)ALLoader.DefaultALCGetProcAddress(AllFunctionNames.Slice(SetAudioChannel_LOKI_offset));
            ALLoader.Default.ALC._pointers->_SetAudioChannel_LOKI_fnptr = fnptr;
            fnptr(channel, volume);
        }
        
    }
}
