// <auto-generated />
// This file is auto generated, do not edit.
#nullable enable
using System;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using OpenTK.Core.Native;
using OpenTK.Mathematics;
using OpenTK.Audio;

namespace OpenTK.Audio.OpenAL
{
    /// <summary>Exposes all the AL functions loaded by ALLoader.</summary>
    public readonly unsafe partial struct AL
    {
        internal readonly ALPointers* _pointers;
        internal readonly ALPointers[] _pointersPinnedArray;
        /// <summary>The reference to the container of function pointers loaded by ALLoader.</summary>
        public ref readonly ALPointers Pointers => ref Unsafe.AsRef<ALPointers>(_pointers);
        
        /// <summary>
        /// Initializes a new instance of the <see cref="AL"/> struct.
        /// </summary>
        /// <param name="pointers">The <see cref="ALPointers"/> to initialize with.</param>
        /// <param name="pointersPinnedArray">The place <see cref="ALPointers"/> resides.</param>
        public AL(ALPointers* pointers, ALPointers[] pointersPinnedArray)
        {
            _pointers = pointers;
            _pointersPinnedArray = pointersPinnedArray;
        }
        /// <summary>Creative extensions.</summary>
        public ALExtensions.Creative Creative => new(this);
        /// <summary>Direct extensions.</summary>
        public ALExtensions.Direct Direct => new(this);
        /// <summary>EXT extensions.</summary>
        public ALExtensions.EXT EXT => new(this);
        /// <summary>LOKI extensions.</summary>
        public ALExtensions.LOKI LOKI => new(this);
        /// <summary>SOFT extensions.</summary>
        public ALExtensions.SOFT SOFT => new(this);
    }
    
    /// <summary>Contains extensions' pointer containers.</summary>
    public static partial class ALExtensions
    {
        /// <summary>Interface for ALPointers containers.</summary>
        public interface IALContainer
        {
            /// <summary>The underlying AL object.</summary>
            AL AL { get; }
        }
        
        /// <summary>The ALPointers container for AL_EXT_direct_context extensions.</summary>
        public readonly record struct Direct<TDependentAPIVendor>(TDependentAPIVendor vendor) : IALContainer where TDependentAPIVendor : struct, IALContainer
        {
            /// <inheritdoc/>
            public AL AL => vendor.AL;
        }
        
        /// <summary>Creative extensions.</summary>
        public readonly record struct Creative(AL AL) : IALContainer
        {
            /// <summary>AL_EXT_direct_context extensions for Creative extensions.</summary>
            public Direct<Creative> Direct => new(this);
        }
        
        /// <summary>Direct extensions.</summary>
        public readonly record struct Direct(AL AL) : IALContainer
        {
        }
        
        /// <summary>EXT extensions.</summary>
        public readonly record struct EXT(AL AL) : IALContainer
        {
            /// <summary>AL_EXT_direct_context extensions for EXT extensions.</summary>
            public Direct<EXT> Direct => new(this);
        }
        
        /// <summary>LOKI extensions.</summary>
        public readonly record struct LOKI(AL AL) : IALContainer
        {
            /// <summary>AL_EXT_direct_context extensions for LOKI extensions.</summary>
            public Direct<LOKI> Direct => new(this);
        }
        
        /// <summary>SOFT extensions.</summary>
        public readonly record struct SOFT(AL AL) : IALContainer
        {
            /// <summary>AL_EXT_direct_context extensions for SOFT extensions.</summary>
            public Direct<SOFT> Direct => new(this);
        }
    }
}
