// <auto-generated />
// This file is auto generated, do not edit.
#nullable enable
using System;
using System.Buffers;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using OpenTK.Audio;
using OpenTK.Core.Native;
using OpenTK.Mathematics;

namespace OpenTK.Audio.OpenAL
{
    /// <summary>Exposes all the AL functions loaded by ALLoader.</summary>
    public readonly unsafe ref partial struct AL
    {
        internal readonly ref readonly ALPointers _pointers;
        /// <summary>The reference to the container of function pointers loaded by ALLoader.</summary>
        public ref readonly ALPointers Pointers => ref _pointers;
        
        /// <summary>
        /// Initializes a new instance of the <see cref="AL"/> struct.
        /// </summary>
        /// <param name="pointers">The <see cref="ALPointers"/> to initialize with.</param>
        public AL(ref readonly ALPointers pointers)
        {
            _pointers = ref pointers;
        }
        /// <summary>Creative extensions.</summary>
        public ALExtensions.Creative Creative => new(this);
        /// <summary>Direct extensions.</summary>
        public ALExtensions.Direct Direct => new(this);
        /// <summary>EXT extensions.</summary>
        public ALExtensions.EXT EXT => new(this);
        /// <summary>LOKI extensions.</summary>
        public ALExtensions.LOKI LOKI => new(this);
        /// <summary>SOFT extensions.</summary>
        public ALExtensions.SOFT SOFT => new(this);
    }
    
    /// <summary>Contains extensions' pointer containers.</summary>
    public static partial class ALExtensions
    {
        /// <summary>Interface for ALPointers containers.</summary>
        public interface IALContainer
        {
            /// <summary>The underlying AL object.</summary>
            AL AL { get; }
        }
        
        /// <summary>The ALPointers container for AL_EXT_direct_context extensions.</summary>
        public readonly unsafe ref partial struct Direct<TDependentAPIVendor>(TDependentAPIVendor vendor) : IALContainer where TDependentAPIVendor : struct, IALContainer, allows ref struct
        {
            /// <inheritdoc/>
            public AL AL { get; } = vendor.AL;
        }
        
        /// <summary>Creative extensions.</summary>
        public readonly unsafe ref partial struct Creative(AL al) : IALContainer
        {
            /// <inheritdoc/>
            public AL AL { get; } = al;
            /// <summary>AL_EXT_direct_context extensions for Creative extensions.</summary>
            public Direct<Creative> Direct => new(this);
        }
        
        /// <summary>Direct extensions.</summary>
        public readonly unsafe ref partial struct Direct(AL al) : IALContainer
        {
            /// <inheritdoc/>
            public AL AL { get; } = al;
        }
        
        /// <summary>EXT extensions.</summary>
        public readonly unsafe ref partial struct EXT(AL al) : IALContainer
        {
            /// <inheritdoc/>
            public AL AL { get; } = al;
            /// <summary>AL_EXT_direct_context extensions for EXT extensions.</summary>
            public Direct<EXT> Direct => new(this);
        }
        
        /// <summary>LOKI extensions.</summary>
        public readonly unsafe ref partial struct LOKI(AL al) : IALContainer
        {
            /// <inheritdoc/>
            public AL AL { get; } = al;
            /// <summary>AL_EXT_direct_context extensions for LOKI extensions.</summary>
            public Direct<LOKI> Direct => new(this);
        }
        
        /// <summary>SOFT extensions.</summary>
        public readonly unsafe ref partial struct SOFT(AL al) : IALContainer
        {
            /// <inheritdoc/>
            public AL AL { get; } = al;
            /// <summary>AL_EXT_direct_context extensions for SOFT extensions.</summary>
            public Direct<SOFT> Direct => new(this);
        }
    }
}
