// <auto-generated />
// This file is auto generated, do not edit.
#nullable enable
using System;
using System.Buffers;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using OpenTK.Audio;
using OpenTK.Core.Native;
using OpenTK.Mathematics;

namespace OpenTK.Audio.OpenAL.ALC
{
    /// <summary>Exposes all the ALC functions loaded by ALCLoader.</summary>
    public readonly unsafe ref partial struct ALC
    {
        internal readonly ref readonly ALCPointers _pointers;
        /// <summary>The reference to the container of function pointers loaded by ALCLoader.</summary>
        public ref readonly ALCPointers Pointers => ref _pointers;
        
        /// <summary>
        /// Initializes a new instance of the <see cref="ALC"/> struct.
        /// </summary>
        /// <param name="pointers">The <see cref="ALCPointers"/> to initialize with.</param>
        public ALC(ref readonly ALCPointers pointers)
        {
            _pointers = ref pointers;
        }
        /// <summary>Direct extensions.</summary>
        public ALCExtensions.Direct Direct => new(this);
        /// <summary>EXT extensions.</summary>
        public ALCExtensions.EXT EXT => new(this);
        /// <summary>LOKI extensions.</summary>
        public ALCExtensions.LOKI LOKI => new(this);
        /// <summary>SOFT extensions.</summary>
        public ALCExtensions.SOFT SOFT => new(this);
    }
    
    /// <summary>Contains extensions' pointer containers.</summary>
    public static partial class ALCExtensions
    {
        /// <summary>Interface for ALCPointers containers.</summary>
        public interface IALCContainer
        {
            /// <summary>The underlying ALC object.</summary>
            ALC ALC { get; }
        }
        
        
        /// <summary>Direct extensions.</summary>
        public readonly unsafe ref partial struct Direct(ALC alc) : IALCContainer
        {
            /// <inheritdoc/>
            public ALC ALC { get; } = alc;
        }
        
        /// <summary>EXT extensions.</summary>
        public readonly unsafe ref partial struct EXT(ALC alc) : IALCContainer
        {
            /// <inheritdoc/>
            public ALC ALC { get; } = alc;
        }
        
        /// <summary>LOKI extensions.</summary>
        public readonly unsafe ref partial struct LOKI(ALC alc) : IALCContainer
        {
            /// <inheritdoc/>
            public ALC ALC { get; } = alc;
        }
        
        /// <summary>SOFT extensions.</summary>
        public readonly unsafe ref partial struct SOFT(ALC alc) : IALCContainer
        {
            /// <inheritdoc/>
            public ALC ALC { get; } = alc;
        }
    }
}
