// <auto-generated />
// This file is auto generated, do not edit.
#nullable enable
using System;
using System.Buffers;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using OpenTK.Audio;
using OpenTK.Core.Native;
using OpenTK.Mathematics;

namespace OpenTK.Audio.OpenAL.ALC
{
    public static unsafe partial class ALCFunctions
    {
        /// <summary> <b>[requires: v1.1 | ALC_EXT_CAPTURE]</b> <b>[entry point: <c>alcCaptureCloseDevice</c>]</b><br/>  </summary>
        /// <param name="alc">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_CAPTURE.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool CaptureCloseDevice(this ALC alc, ALCDevice device) => 0 != alc._pointers->_alcCaptureCloseDevice_fnptr((IntPtr)device);
        
        /// <summary> <b>[requires: v1.1 | ALC_EXT_CAPTURE]</b> <b>[entry point: <c>alcCaptureOpenDevice</c>]</b><br/>  </summary>
        /// <param name="alc">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_CAPTURE.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ALCDevice CaptureOpenDevice(this ALC alc, byte* devicename, uint frequency, Format format, int buffersize) => (ALCDevice) alc._pointers->_alcCaptureOpenDevice_fnptr(devicename, frequency, (int)format, buffersize);
        
        /// <summary> <b>[requires: v1.1 | ALC_EXT_CAPTURE]</b> <b>[entry point: <c>alcCaptureSamples</c>]</b><br/>  </summary>
        /// <param name="alc">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_CAPTURE.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void CaptureSamples(this ALC alc, ALCDevice device, void* buffer, int samples) => alc._pointers->_alcCaptureSamples_fnptr((IntPtr)device, buffer, samples);
        
        /// <summary> <b>[requires: v1.1 | ALC_EXT_CAPTURE]</b> <b>[entry point: <c>alcCaptureStart</c>]</b><br/>  </summary>
        /// <param name="alc">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_CAPTURE.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void CaptureStart(this ALC alc, ALCDevice device) => alc._pointers->_alcCaptureStart_fnptr((IntPtr)device);
        
        /// <summary> <b>[requires: v1.1 | ALC_EXT_CAPTURE]</b> <b>[entry point: <c>alcCaptureStop</c>]</b><br/>  </summary>
        /// <param name="alc">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_CAPTURE.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void CaptureStop(this ALC alc, ALCDevice device) => alc._pointers->_alcCaptureStop_fnptr((IntPtr)device);
        
        /// <summary> <b>[requires: v1.0]</b> <b>[entry point: <c>alcCloseDevice</c>]</b><br/>  </summary>
        /// <param name="alc">The container of native function pointers.</param>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool CloseDevice(this ALC alc, ALCDevice device) => 0 != alc._pointers->_alcCloseDevice_fnptr((IntPtr)device);
        
        /// <summary> <b>[requires: v1.0]</b> <b>[entry point: <c>alcCreateContext</c>]</b><br/>  </summary>
        /// <param name="alc">The container of native function pointers.</param>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ALCContext CreateContext(this ALC alc, ALCDevice device, int* attrlist) => (ALCContext) alc._pointers->_alcCreateContext_fnptr((IntPtr)device, attrlist);
        
        /// <summary> <b>[requires: v1.0]</b> <b>[entry point: <c>alcDestroyContext</c>]</b><br/>  </summary>
        /// <param name="alc">The container of native function pointers.</param>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void DestroyContext(this ALC alc, ALCContext context) => alc._pointers->_alcDestroyContext_fnptr((IntPtr)context);
        
        /// <summary> <b>[requires: v1.0]</b> <b>[entry point: <c>alcGetContextsDevice</c>]</b><br/>  </summary>
        /// <param name="alc">The container of native function pointers.</param>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ALCDevice GetContextsDevice(this ALC alc, ALCContext context) => (ALCDevice) alc._pointers->_alcGetContextsDevice_fnptr((IntPtr)context);
        
        /// <summary> <b>[requires: v1.0]</b> <b>[entry point: <c>alcGetCurrentContext</c>]</b><br/>  </summary>
        /// <param name="alc">The container of native function pointers.</param>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ALCContext GetCurrentContext(this ALC alc) => (ALCContext) alc._pointers->_alcGetCurrentContext_fnptr();
        
        /// <summary> <b>[requires: v1.0]</b> <b>[entry point: <c>alcGetEnumValue</c>]</b><br/>  </summary>
        /// <param name="alc">The container of native function pointers.</param>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static All GetEnumValue(this ALC alc, ALCDevice device, byte* enumname) => (All) alc._pointers->_alcGetEnumValue_fnptr((IntPtr)device, enumname);
        
        /// <summary> <b>[requires: v1.0]</b> <b>[entry point: <c>alcGetError</c>]</b><br/>  </summary>
        /// <param name="alc">The container of native function pointers.</param>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ErrorCode GetError(this ALC alc, ALCDevice device) => (ErrorCode) alc._pointers->_alcGetError_fnptr((IntPtr)device);
        
        /// <summary> <b>[requires: v1.0]</b> <b>[entry point: <c>alcGetIntegerv</c>]</b><br/>  </summary>
        /// <param name="alc">The container of native function pointers.</param>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void GetIntegerv(this ALC alc, ALCDevice device, GetPNameIV param, int size, int* values) => alc._pointers->_alcGetIntegerv_fnptr((IntPtr)device, (int)param, size, values);
        
        /// <summary> <b>[requires: v1.0]</b> <b>[entry point: <c>alcGetProcAddress</c>]</b><br/>  </summary>
        /// <param name="alc">The container of native function pointers.</param>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void* GetProcAddress(this ALC alc, ALCDevice device, byte* extname) => alc._pointers->_alcGetProcAddress_fnptr((IntPtr)device, extname);
        
        /// <summary> <b>[requires: v1.0]</b> <b>[entry point: <c>alcGetString</c>]</b><br/>  </summary>
        /// <param name="alc">The container of native function pointers.</param>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static byte* GetString_(this ALC alc, ALCDevice device, StringName param) => alc._pointers->_alcGetString_fnptr((IntPtr)device, (int)param);
        
        /// <summary> <b>[requires: v1.0]</b> <b>[entry point: <c>alcIsExtensionPresent</c>]</b><br/>  </summary>
        /// <param name="alc">The container of native function pointers.</param>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool IsExtensionPresent(this ALC alc, ALCDevice deviceHandle, byte* extname) => 0 != alc._pointers->_alcIsExtensionPresent_fnptr((IntPtr)deviceHandle, extname);
        
        /// <summary> <b>[requires: v1.0]</b> <b>[entry point: <c>alcMakeContextCurrent</c>]</b><br/>  </summary>
        /// <param name="alc">The container of native function pointers.</param>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool MakeContextCurrent(this ALC alc, ALCContext context) => 0 != alc._pointers->_alcMakeContextCurrent_fnptr((IntPtr)context);
        
        /// <summary> <b>[requires: v1.0]</b> <b>[entry point: <c>alcOpenDevice</c>]</b><br/>  </summary>
        /// <param name="alc">The container of native function pointers.</param>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ALCDevice OpenDevice(this ALC alc, byte* devicename) => (ALCDevice) alc._pointers->_alcOpenDevice_fnptr(devicename);
        
        /// <summary> <b>[requires: v1.0]</b> <b>[entry point: <c>alcProcessContext</c>]</b><br/>  </summary>
        /// <param name="alc">The container of native function pointers.</param>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void ProcessContext(this ALC alc, ALCContext context) => alc._pointers->_alcProcessContext_fnptr((IntPtr)context);
        
        /// <summary> <b>[requires: v1.0]</b> <b>[entry point: <c>alcSuspendContext</c>]</b><br/>  </summary>
        /// <param name="alc">The container of native function pointers.</param>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void SuspendContext(this ALC alc, ALCContext context) => alc._pointers->_alcSuspendContext_fnptr((IntPtr)context);
        
        /// <summary> <b>[requires: ALC_EXT_direct_context]</b> <b>[entry point: <c>alcGetProcAddress2</c>]</b><br/>  </summary>
        /// <param name="direct">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_direct_context.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void* GetProcAddress2(this ALCExtensions.Direct direct, ALCDevice device, byte* funcName) => direct.ALC._pointers->_alcGetProcAddress2_fnptr((IntPtr)device, funcName);
        
        /// <summary> <b>[requires: ALC_EXT_ASA]</b> <b>[entry point: <c>alcASAGetListener</c>]</b><br/>  </summary>
        /// <param name="ext">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_ASA.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static All ASAGetListener(this ALCExtensions.EXT ext, uint property, void* data, uint* dataSize) => (All) ext.ALC._pointers->_alcASAGetListener_fnptr(property, data, dataSize);
        
        /// <summary> <b>[requires: ALC_EXT_ASA]</b> <b>[entry point: <c>alcASAGetSource</c>]</b><br/>  </summary>
        /// <param name="ext">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_ASA.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static All ASAGetSource(this ALCExtensions.EXT ext, uint property, uint source, void* data, uint* dataSize) => (All) ext.ALC._pointers->_alcASAGetSource_fnptr(property, source, data, dataSize);
        
        /// <summary> <b>[requires: ALC_EXT_ASA]</b> <b>[entry point: <c>alcASASetListener</c>]</b><br/>  </summary>
        /// <param name="ext">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_ASA.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static All ASASetListener(this ALCExtensions.EXT ext, uint property, void* data, uint dataSize) => (All) ext.ALC._pointers->_alcASASetListener_fnptr(property, data, dataSize);
        
        /// <summary> <b>[requires: ALC_EXT_ASA]</b> <b>[entry point: <c>alcASASetSource</c>]</b><br/>  </summary>
        /// <param name="ext">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_ASA.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static All ASASetSource(this ALCExtensions.EXT ext, uint property, uint source, void* data, uint dataSize) => (All) ext.ALC._pointers->_alcASASetSource_fnptr(property, source, data, dataSize);
        
        /// <summary> <b>[requires: v1.1 | ALC_EXT_CAPTURE]</b> <b>[entry point: <c>alcCaptureCloseDevice</c>]</b><br/>  </summary>
        /// <param name="ext">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_CAPTURE.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool CaptureCloseDevice(this ALCExtensions.EXT ext, ALCDevice device) => 0 != ext.ALC._pointers->_alcCaptureCloseDevice_fnptr((IntPtr)device);
        
        /// <summary> <b>[requires: v1.1 | ALC_EXT_CAPTURE]</b> <b>[entry point: <c>alcCaptureOpenDevice</c>]</b><br/>  </summary>
        /// <param name="ext">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_CAPTURE.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ALCDevice CaptureOpenDevice(this ALCExtensions.EXT ext, byte* devicename, uint frequency, Format format, int buffersize) => (ALCDevice) ext.ALC._pointers->_alcCaptureOpenDevice_fnptr(devicename, frequency, (int)format, buffersize);
        
        /// <summary> <b>[requires: v1.1 | ALC_EXT_CAPTURE]</b> <b>[entry point: <c>alcCaptureSamples</c>]</b><br/>  </summary>
        /// <param name="ext">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_CAPTURE.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void CaptureSamples(this ALCExtensions.EXT ext, ALCDevice device, void* buffer, int samples) => ext.ALC._pointers->_alcCaptureSamples_fnptr((IntPtr)device, buffer, samples);
        
        /// <summary> <b>[requires: v1.1 | ALC_EXT_CAPTURE]</b> <b>[entry point: <c>alcCaptureStart</c>]</b><br/>  </summary>
        /// <param name="ext">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_CAPTURE.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void CaptureStart(this ALCExtensions.EXT ext, ALCDevice device) => ext.ALC._pointers->_alcCaptureStart_fnptr((IntPtr)device);
        
        /// <summary> <b>[requires: v1.1 | ALC_EXT_CAPTURE]</b> <b>[entry point: <c>alcCaptureStop</c>]</b><br/>  </summary>
        /// <param name="ext">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_CAPTURE.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void CaptureStop(this ALCExtensions.EXT ext, ALCDevice device) => ext.ALC._pointers->_alcCaptureStop_fnptr((IntPtr)device);
        
        /// <summary> <b>[requires: ALC_EXT_thread_local_context]</b> <b>[entry point: <c>alcGetThreadContext</c>]</b><br/>  </summary>
        /// <param name="ext">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_thread_local_context.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ALCContext GetThreadContext(this ALCExtensions.EXT ext) => (ALCContext) ext.ALC._pointers->_alcGetThreadContext_fnptr();
        
        /// <summary> <b>[requires: ALC_EXT_MAC_OSX]</b> <b>[entry point: <c>alcMacOSXGetMixerMaxiumumBusses</c>]</b><br/>  </summary>
        /// <param name="ext">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_MAC_OSX.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int MacOSXGetMixerMaxiumumBusses(this ALCExtensions.EXT ext) => ext.ALC._pointers->_alcMacOSXGetMixerMaxiumumBusses_fnptr();
        
        /// <summary> <b>[requires: ALC_EXT_MAC_OSX]</b> <b>[entry point: <c>alcMacOSXGetMixerOutputRate</c>]</b><br/>  </summary>
        /// <param name="ext">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_MAC_OSX.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static double MacOSXGetMixerOutputRate(this ALCExtensions.EXT ext) => ext.ALC._pointers->_alcMacOSXGetMixerOutputRate_fnptr();
        
        /// <summary> <b>[requires: ALC_EXT_MAC_OSX]</b> <b>[entry point: <c>alcMacOSXGetRenderingQuality</c>]</b><br/>  </summary>
        /// <param name="ext">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_MAC_OSX.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int MacOSXGetRenderingQuality(this ALCExtensions.EXT ext) => ext.ALC._pointers->_alcMacOSXGetRenderingQuality_fnptr();
        
        /// <summary> <b>[requires: ALC_EXT_MAC_OSX]</b> <b>[entry point: <c>alcMacOSXMixerMaxiumumBusses</c>]</b><br/>  </summary>
        /// <param name="ext">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_MAC_OSX.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void MacOSXMixerMaxiumumBusses(this ALCExtensions.EXT ext, int value) => ext.ALC._pointers->_alcMacOSXMixerMaxiumumBusses_fnptr(value);
        
        /// <summary> <b>[requires: ALC_EXT_MAC_OSX]</b> <b>[entry point: <c>alcMacOSXMixerOutputRate</c>]</b><br/>  </summary>
        /// <param name="ext">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_MAC_OSX.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void MacOSXMixerOutputRate(this ALCExtensions.EXT ext, double value) => ext.ALC._pointers->_alcMacOSXMixerOutputRate_fnptr(value);
        
        /// <summary> <b>[requires: ALC_EXT_MAC_OSX]</b> <b>[entry point: <c>alcMacOSXRenderingQuality</c>]</b><br/>  </summary>
        /// <param name="ext">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_MAC_OSX.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void MacOSXRenderingQuality(this ALCExtensions.EXT ext, int value) => ext.ALC._pointers->_alcMacOSXRenderingQuality_fnptr(value);
        
        /// <summary> <b>[requires: ALC_EXT_OUTPUT_CAPTURER]</b> <b>[entry point: <c>alcOutputCapturerAvailableSamples</c>]</b><br/>  </summary>
        /// <param name="ext">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_OUTPUT_CAPTURER.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void OutputCapturerAvailableSamples(this ALCExtensions.EXT ext) => ext.ALC._pointers->_alcOutputCapturerAvailableSamples_fnptr();
        
        /// <summary> <b>[requires: ALC_EXT_OUTPUT_CAPTURER]</b> <b>[entry point: <c>alcOutputCapturerPrepare</c>]</b><br/>  </summary>
        /// <param name="ext">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_OUTPUT_CAPTURER.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void OutputCapturerPrepare(this ALCExtensions.EXT ext, uint frequency, All format, int maxsamplecount) => ext.ALC._pointers->_alcOutputCapturerPrepare_fnptr(frequency, (int)format, maxsamplecount);
        
        /// <summary> <b>[requires: ALC_EXT_OUTPUT_CAPTURER]</b> <b>[entry point: <c>alcOutputCapturerSamples</c>]</b><br/>  </summary>
        /// <param name="ext">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_OUTPUT_CAPTURER.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void OutputCapturerSamples(this ALCExtensions.EXT ext, void* buffer, int maxsamplecount) => ext.ALC._pointers->_alcOutputCapturerSamples_fnptr(buffer, maxsamplecount);
        
        /// <summary> <b>[requires: ALC_EXT_OUTPUT_CAPTURER]</b> <b>[entry point: <c>alcOutputCapturerStart</c>]</b><br/>  </summary>
        /// <param name="ext">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_OUTPUT_CAPTURER.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void OutputCapturerStart(this ALCExtensions.EXT ext) => ext.ALC._pointers->_alcOutputCapturerStart_fnptr();
        
        /// <summary> <b>[requires: ALC_EXT_OUTPUT_CAPTURER]</b> <b>[entry point: <c>alcOutputCapturerStop</c>]</b><br/>  </summary>
        /// <param name="ext">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_OUTPUT_CAPTURER.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void OutputCapturerStop(this ALCExtensions.EXT ext) => ext.ALC._pointers->_alcOutputCapturerStop_fnptr();
        
        /// <summary> <b>[requires: ALC_EXT_thread_local_context]</b> <b>[entry point: <c>alcSetThreadContext</c>]</b><br/>  </summary>
        /// <param name="ext">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_EXT_thread_local_context.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool SetThreadContext(this ALCExtensions.EXT ext, ALCContext context) => 0 != ext.ALC._pointers->_alcSetThreadContext_fnptr((IntPtr)context);
        
        /// <summary> <b>[requires: ALC_LOKI_audio_channel]</b> <b>[entry point: <c>GetAudioChannel_LOKI</c>]</b><br/>  </summary>
        /// <param name="loki">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_LOKI_audio_channel.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static float GetAudioChannel_LOKI(this ALCExtensions.LOKI loki, uint channel) => loki.ALC._pointers->_GetAudioChannel_LOKI_fnptr(channel);
        
        /// <summary> <b>[requires: ALC_LOKI_audio_channel]</b> <b>[entry point: <c>SetAudioChannel_LOKI</c>]</b><br/>  </summary>
        /// <param name="loki">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_LOKI_audio_channel.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void SetAudioChannel_LOKI(this ALCExtensions.LOKI loki, uint channel, float volume) => loki.ALC._pointers->_SetAudioChannel_LOKI_fnptr(channel, volume);
        
        /// <summary> <b>[requires: ALC_SOFT_pause_device]</b> <b>[entry point: <c>alcDevicePauseSOFT</c>]</b><br/>  </summary>
        /// <param name="soft">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_SOFT_pause_device.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void DevicePauseSOFT(this ALCExtensions.SOFT soft, ALCDevice device) => soft.ALC._pointers->_alcDevicePauseSOFT_fnptr((IntPtr)device);
        
        /// <summary> <b>[requires: ALC_SOFT_pause_device]</b> <b>[entry point: <c>alcDeviceResumeSOFT</c>]</b><br/>  </summary>
        /// <param name="soft">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_SOFT_pause_device.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void DeviceResumeSOFT(this ALCExtensions.SOFT soft, ALCDevice device) => soft.ALC._pointers->_alcDeviceResumeSOFT_fnptr((IntPtr)device);
        
        /// <summary> <b>[requires: ALC_SOFT_system_events]</b> <b>[entry point: <c>alcEventCallbackSOFT</c>]</b><br/>  </summary>
        /// <param name="soft">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_SOFT_system_events.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void EventCallbackSOFT(this ALCExtensions.SOFT soft, delegate* unmanaged[Cdecl]<All, All, ALCDevice, nuint, byte*, void*, void> callback, void* userParam) => soft.ALC._pointers->_alcEventCallbackSOFT_fnptr(callback, userParam);
        
        /// <summary> <b>[requires: ALC_SOFT_system_events]</b> <b>[entry point: <c>alcEventControlSOFT</c>]</b><br/>  </summary>
        /// <param name="soft">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_SOFT_system_events.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool EventControlSOFT(this ALCExtensions.SOFT soft, int count, EventType* events, bool enable) => 0 != soft.ALC._pointers->_alcEventControlSOFT_fnptr(count, (int*)events, (byte)(enable ? 1 : 0));
        
        /// <summary> <b>[requires: ALC_SOFT_system_events]</b> <b>[entry point: <c>alcEventIsSupportedSOFT</c>]</b><br/>  </summary>
        /// <param name="soft">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_SOFT_system_events.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static EventSupport EventIsSupportedSOFT(this ALCExtensions.SOFT soft, EventType eventType, DeviceType deviceType) => (EventSupport) soft.ALC._pointers->_alcEventIsSupportedSOFT_fnptr((int)eventType, (int)deviceType);
        
        /// <summary> <b>[requires: ALC_SOFT_device_clock]</b> <b>[entry point: <c>alcGetInteger64vSOFT</c>]</b><br/>  </summary>
        /// <param name="soft">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_SOFT_device_clock.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void GetInteger64vSOFT(this ALCExtensions.SOFT soft, ALCDevice device, GetPNameI64V pname, int size, long* values) => soft.ALC._pointers->_alcGetInteger64vSOFT_fnptr((IntPtr)device, (int)pname, size, values);
        
        /// <summary> <b>[requires: ALC_SOFT_HRTF]</b> <b>[entry point: <c>alcGetStringiSOFT</c>]</b><br/>  </summary>
        /// <param name="soft">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_SOFT_HRTF.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static byte* GetStringiSOFT_(this ALCExtensions.SOFT soft, ALCDevice device, IndexedStringName paramName, int index) => soft.ALC._pointers->_alcGetStringiSOFT_fnptr((IntPtr)device, (int)paramName, index);
        
        /// <summary> <b>[requires: ALC_SOFT_loopback]</b> <b>[entry point: <c>alcIsRenderFormatSupportedSOFT</c>]</b><br/>  </summary>
        /// <param name="soft">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_SOFT_loopback.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool IsRenderFormatSupportedSOFT(this ALCExtensions.SOFT soft, ALCDevice device, int frequency, RenderFormatChannels channels, RenderFormatType type) => 0 != soft.ALC._pointers->_alcIsRenderFormatSupportedSOFT_fnptr((IntPtr)device, frequency, (int)channels, (int)type);
        
        /// <summary> <b>[requires: ALC_SOFT_loopback]</b> <b>[entry point: <c>alcLoopbackOpenDeviceSOFT</c>]</b><br/>  </summary>
        /// <param name="soft">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_SOFT_loopback.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ALCDevice LoopbackOpenDeviceSOFT(this ALCExtensions.SOFT soft, ALCDevice device) => (ALCDevice) soft.ALC._pointers->_alcLoopbackOpenDeviceSOFT_fnptr((IntPtr)device);
        
        /// <summary> <b>[requires: ALC_SOFT_loopback]</b> <b>[entry point: <c>alcRenderSamplesSOFT</c>]</b><br/>  </summary>
        /// <param name="soft">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_SOFT_loopback.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void RenderSamplesSOFT(this ALCExtensions.SOFT soft, ALCDevice device, void* buffer, int samples) => soft.ALC._pointers->_alcRenderSamplesSOFT_fnptr((IntPtr)device, buffer, samples);
        
        /// <summary> <b>[requires: ALC_SOFT_reopen_device]</b> <b>[entry point: <c>alcReopenDeviceSOFT</c>]</b><br/>  </summary>
        /// <param name="soft">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_SOFT_reopen_device.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool ReopenDeviceSOFT(this ALCExtensions.SOFT soft, ALCDevice device, byte* deviceName, int* attribs) => 0 != soft.ALC._pointers->_alcReopenDeviceSOFT_fnptr((IntPtr)device, deviceName, attribs);
        
        /// <summary> <b>[requires: ALC_SOFT_HRTF | ALC_SOFT_output_limiter]</b> <b>[entry point: <c>alcResetDeviceSOFT</c>]</b><br/>  </summary>
        /// <param name="soft">The container of native function pointers.</param>
        /// <remarks><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_SOFT_HRTF.txt"/><br/><see href="https://raw.githubusercontent.com/Raulshc/OpenAL-EXT-Repository/refs/heads/master/ALC%20Extensions/ALC_SOFT_output_limiter.txt"/></remarks>
        [OverloadResolutionPriority(short.MinValue)]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool ResetDeviceSOFT(this ALCExtensions.SOFT soft, ALCDevice device, int* attrList) => 0 != soft.ALC._pointers->_alcResetDeviceSOFT_fnptr((IntPtr)device, attrList);
        
    }
}
